import * as encoders from "../encoders/index.js";

export const advancedEncoders = [
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate scannable QR codes (client-side ASCII art)",
    emoji: "📱",
    category: "advanced",
    encode: encoders.encodeQRCode,
    reversible: false,
    tags: ["advanced", "qr", "mobile"],
  },
  {
    id: "url-encode",
    name: "URL Encoding",
    description: "Web-safe URL encoding",
    emoji: "🔗",
    category: "advanced",
    encode: encoders.encodeURL,
    decode: encoders.decodeURL,
    reversible: true,
    tags: ["advanced", "web", "url"],
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "HTML-safe character encoding",
    emoji: "🌐",
    category: "advanced",
    encode: encoders.encodeHTMLEntities,
    decode: encoders.decodeHTMLEntities,
    reversible: true,
    tags: ["advanced", "web", "html"],
  },
  {
    id: "sound-wave",
    name: "Sound Wave",
    description: "Visual sound wave representation",
    emoji: "🔊",
    category: "advanced",
    encode: encoders.encodeSoundWave,
    reversible: false,
    tags: ["advanced", "visual", "audio"],
  },
  {
    id: "hash",
    name: "Hash Generator",
    description: "Generate unique hash from text",
    emoji: "🔐",
    category: "advanced",
    encode: encoders.encodeHash,
    reversible: false,
    tags: ["advanced", "hash", "fingerprint"],
  },
  {
    id: "shuffle",
    name: "Shuffle Encoding",
    description:
      "Each character encoded with a random encoder from selected options",
    emoji: "🔀",
    category: "advanced",
    encode: encoders.encodeShuffle,
    decode: encoders.decodeShuffle,
    reversible: false,
    hasSettings: true,
    tags: ["advanced", "shuffle", "random", "mixed"],
  },
  {
    id: "military-grid",
    name: "Military Grid",
    description: "Military grid reference format",
    emoji: "🗺️",
    category: "advanced",
    encode: encoders.encodeMilitaryGrid,
    reversible: false,
    tags: ["advanced", "military", "grid"],
  },
  {
    id: "waypoint",
    name: "Aviation Waypoint",
    description: "Aviation waypoint format",
    emoji: "✈️",
    category: "advanced",
    encode: encoders.encodeWaypoint,
    reversible: false,
    tags: ["advanced", "aviation", "waypoint"],
  },
  {
    id: "metar",
    name: "METAR Weather",
    description: "Aviation weather report format",
    emoji: "🌤️",
    category: "advanced",
    encode: encoders.encodeMETAR,
    reversible: false,
    tags: ["advanced", "aviation", "weather"],
  },
  {
    id: "notam",
    name: "NOTAM Format",
    description: "Notice to Airmen format",
    emoji: "⚠️",
    category: "advanced",
    encode: encoders.encodeNOTAM,
    reversible: false,
    tags: ["advanced", "aviation", "notam"],
  },
];
