import * as encoders from "../encoders/index.js";

export const aestheticEncoders = [
  {
    id: "fullwidth",
    name: "Ｆｕｌｌｗｉｄｔｈ Ｔｅｘｔ",
    description: "Wide aesthetic characters",
    emoji: "↔️",
    category: "aesthetic",
    encode: encoders.encodeFullwidth,
    decode: encoders.decodeFullwidth,
    reversible: true,
    tags: ["aesthetic", "wide", "vaporwave"],
  },
  {
    id: "squared",
    name: "🅂🅀🅄🄰🅁🄴🄳 🅃🄴🅇🅃",
    description: "Squared Unicode letters",
    emoji: "🔲",
    category: "aesthetic",
    encode: encoders.encodeSquared,
    decode: encoders.decodeSquared,
    reversible: false,
    tags: ["aesthetic", "squared", "unicode"],
  },
  {
    id: "parenthesized",
    name: "⒫⒜⒭⒠⒩⒯⒣⒠⒮⒤⒵⒠⒟",
    description: "Parenthesized letters",
    emoji: "⒜",
    category: "aesthetic",
    encode: encoders.encodeParenthesized,
    decode: encoders.decodeParenthesized,
    reversible: false,
    tags: ["aesthetic", "parenthesized", "unicode"],
  },
  {
    id: "double-struck",
    name: "𝔻𝕠𝕦𝕓𝕝𝕖 𝕊𝕥𝕣𝕦𝕔𝕜",
    description: "Mathematical blackboard bold",
    emoji: "🎯",
    category: "aesthetic",
    encode: encoders.encodeDoubleStruck,
    decode: encoders.decodeDoubleStruck,
    reversible: true,
    tags: ["aesthetic", "doublestruck", "math"],
  },
  {
    id: "cursive",
    name: "𝒞𝓊𝓇𝓈𝒾𝓋𝑒 𝒮𝒸𝓇𝒾𝓅𝓉",
    description: "Elegant cursive script",
    emoji: "✒️",
    category: "aesthetic",
    encode: encoders.encodeCursive,
    decode: encoders.decodeCursive,
    reversible: true,
    tags: ["aesthetic", "cursive", "script"],
  },
  {
    id: "mirror",
    name: "Mirror Text",
    description: "Horizontally mirrored text",
    emoji: "🪞",
    category: "aesthetic",
    encode: encoders.encodeMirror,
    reversible: false,
    tags: ["aesthetic", "mirror", "reversed"],
  },
  {
    id: "math-bold",
    name: "𝐌𝐚𝐭𝐡 𝐁𝐨𝐥𝐝",
    description: "Mathematical bold letters",
    emoji: "🔠",
    category: "aesthetic",
    encode: encoders.encodeMathBold,
    reversible: false,
    tags: ["aesthetic", "math", "bold"],
  },
  {
    id: "math-italic",
    name: "𝑀𝑎𝑡ℎ 𝐼𝑡𝑎𝑙𝑖𝑐",
    description: "Mathematical italic letters",
    emoji: "✒️",
    category: "aesthetic",
    encode: encoders.encodeMathItalic,
    reversible: false,
    tags: ["aesthetic", "math", "italic"],
  },
  {
    id: "math-bold-italic",
    name: "𝑴𝒂𝒕𝒉 𝑩𝒐𝒍𝒅 𝑰𝒕𝒂𝒍𝒊𝒄",
    description: "Mathematical bold italic",
    emoji: "📝",
    category: "aesthetic",
    encode: encoders.encodeMathBoldItalic,
    reversible: false,
    tags: ["aesthetic", "math", "bold-italic"],
  },
  {
    id: "math-script",
    name: "𝒮𝒸𝓇𝒾𝓅𝓉",
    description: "Mathematical script (calligraphy)",
    emoji: "✍️",
    category: "aesthetic",
    encode: encoders.encodeMathScript,
    reversible: false,
    tags: ["aesthetic", "math", "script"],
  },
  {
    id: "math-bold-script",
    name: "𝓑𝓸𝓵𝓭 𝓢𝓬𝓻𝓲𝓹𝓽",
    description: "Mathematical bold script",
    emoji: "🖊️",
    category: "aesthetic",
    encode: encoders.encodeMathBoldScript,
    reversible: false,
    tags: ["aesthetic", "math", "bold-script"],
  },
  {
    id: "math-fraktur",
    name: "𝔉𝔯𝔞𝔨𝔱𝔲𝔯",
    description: "Mathematical Fraktur",
    emoji: "⚔️",
    category: "aesthetic",
    encode: encoders.encodeMathFraktur,
    reversible: false,
    tags: ["aesthetic", "math", "fraktur"],
  },
  {
    id: "math-bold-fraktur",
    name: "𝖁𝖔𝖑𝖉 𝕱𝖗𝖆𝖐𝖙𝖚𝖗",
    description: "Mathematical bold Fraktur",
    emoji: "🗡️",
    category: "aesthetic",
    encode: encoders.encodeMathBoldFraktur,
    reversible: false,
    tags: ["aesthetic", "math", "bold-fraktur"],
  },
  {
    id: "math-sans",
    name: "𝖲𝖺𝗇𝗌-𝖲𝖾𝗋𝗂𝖿",
    description: "Mathematical sans-serif",
    emoji: "📋",
    category: "aesthetic",
    encode: encoders.encodeMathSansSerif,
    reversible: false,
    tags: ["aesthetic", "math", "sans-serif"],
  },
  {
    id: "math-sans-bold",
    name: "𝗦𝗮𝗻𝘀 𝗕𝗼𝗹𝗱",
    description: "Mathematical sans-serif bold",
    emoji: "📊",
    category: "aesthetic",
    encode: encoders.encodeMathSansSerifBold,
    reversible: false,
    tags: ["aesthetic", "math", "sans-bold"],
  },
  {
    id: "math-sans-italic",
    name: "𝘚𝘢𝘯𝘴 𝘐𝘵𝘢𝘭𝘪𝘤",
    description: "Mathematical sans-serif italic",
    emoji: "📄",
    category: "aesthetic",
    encode: encoders.encodeMathSansSerifItalic,
    reversible: false,
    tags: ["aesthetic", "math", "sans-italic"],
  },
  {
    id: "math-monospace",
    name: "𝙼𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎",
    description: "Mathematical monospace",
    emoji: "💻",
    category: "aesthetic",
    encode: encoders.encodeMathMonospace,
    reversible: false,
    tags: ["aesthetic", "math", "monospace"],
  },
  {
    id: "circle-overlay",
    name: "C⃝i⃝r⃝c⃝l⃝e⃝ ⃝O⃝v⃝e⃝r⃝l⃝a⃝y⃝",
    description: "Circle around each character",
    emoji: "⭕",
    category: "aesthetic",
    encode: encoders.encodeCircleOverlay,
    reversible: false,
    tags: ["aesthetic", "overlay", "circle"],
  },
  {
    id: "square-overlay",
    name: "S⃞q⃞u⃞a⃞r⃞e⃞ ⃞O⃞v⃞e⃞r⃞l⃞a⃞y⃞",
    description: "Square around each character",
    emoji: "⬜",
    category: "aesthetic",
    encode: encoders.encodeSquareOverlay,
    reversible: false,
    tags: ["aesthetic", "overlay", "square"],
  },
  {
    id: "diamond-overlay",
    name: "D⃟i⃟a⃟m⃟o⃟n⃟d⃟",
    description: "Diamond around each character",
    emoji: "💎",
    category: "aesthetic",
    encode: encoders.encodeDiamondOverlay,
    reversible: false,
    tags: ["aesthetic", "overlay", "diamond"],
  },
  {
    id: "double-underline",
    name: "D̳o̳u̳b̳l̳e̳ ̳U̳n̳d̳e̳r̳l̳i̳n̳e̳",
    description: "Double underlined text",
    emoji: "➖",
    category: "aesthetic",
    encode: encoders.encodeDoubleUnderline,
    reversible: false,
    tags: ["aesthetic", "underline", "double"],
  },
  {
    id: "overline",
    name: "O̅v̅e̅r̅l̅i̅n̅e̅",
    description: "Line above each character",
    emoji: "📏",
    category: "aesthetic",
    encode: encoders.encodeOverline,
    reversible: false,
    tags: ["aesthetic", "overline", "decoration"],
  },
  {
    id: "double-overline",
    name: "D̿o̿u̿b̿l̿e̿ ̿O̿v̿e̿r̿",
    description: "Double line above",
    emoji: "═",
    category: "aesthetic",
    encode: encoders.encodeDoubleOverline,
    reversible: false,
    tags: ["aesthetic", "overline", "double"],
  },
  {
    id: "slash-overlay",
    name: "S̸l̸a̸s̸h̸ ̸O̸v̸e̸r̸l̸a̸y̸",
    description: "Slash through characters",
    emoji: "🚫",
    category: "aesthetic",
    encode: encoders.encodeSlashOverlay,
    reversible: false,
    tags: ["aesthetic", "overlay", "slash"],
  },
  {
    id: "x-overlay",
    name: "X̷ ̷O̷v̷e̷r̷l̷a̷y̷",
    description: "X through characters",
    emoji: "❌",
    category: "aesthetic",
    encode: encoders.encodeXOverlay,
    reversible: false,
    tags: ["aesthetic", "overlay", "x"],
  },
  {
    id: "small-caps",
    name: "ꜱᴍᴀʟʟ ᴄᴀᴘꜱ",
    description: "Small capital letters",
    emoji: "🔡",
    category: "aesthetic",
    encode: encoders.encodeSmallCaps,
    reversible: false,
    tags: ["aesthetic", "smallcaps", "text"],
  },
  {
    id: "subscript-text",
    name: "ₛᵤbₛcᵣᵢₚₜ",
    description: "Subscript text style",
    emoji: "⬇️",
    category: "aesthetic",
    encode: encoders.encodeSubscript,
    reversible: false,
    tags: ["aesthetic", "subscript", "text"],
  },
  {
    id: "regional-indicators",
    name: "🇷🇪🇬🇮🇴🇳🇦🇱",
    description: "Regional indicator symbols",
    emoji: "🏳️",
    category: "aesthetic",
    encode: encoders.encodeRegionalIndicators,
    reversible: false,
    tags: ["aesthetic", "regional", "flags"],
  },
  {
    id: "negative-circled",
    name: "🅝🅔🅖🅐🅣🅘🅥🅔",
    description: "Negative circled letters",
    emoji: "⚫",
    category: "aesthetic",
    encode: encoders.encodeNegativeCircled,
    reversible: false,
    tags: ["aesthetic", "negative", "circled"],
  },
  {
    id: "negative-squared",
    name: "🅽🅴🅶🅰🆃🅸🆅🅴",
    description: "Negative squared letters",
    emoji: "⬛",
    category: "aesthetic",
    encode: encoders.encodeNegativeSquared,
    reversible: false,
    tags: ["aesthetic", "negative", "squared"],
  },
  {
    id: "hearts-between",
    name: "Hearts Between",
    description: "H♥e♥a♥r♥t♥s between chars",
    emoji: "💕",
    category: "aesthetic",
    encode: encoders.encodeHeartsBetween,
    reversible: false,
    tags: ["aesthetic", "hearts", "decoration"],
  },
  {
    id: "stars-between",
    name: "Stars Between",
    description: "S★t★a★r★s between chars",
    emoji: "⭐",
    category: "aesthetic",
    encode: encoders.encodeStarsBetween,
    reversible: false,
    tags: ["aesthetic", "stars", "decoration"],
  },
  {
    id: "dots-between",
    name: "Dots Between",
    description: "D•o•t•s between chars",
    emoji: "🔘",
    category: "aesthetic",
    encode: encoders.encodeDotsBetween,
    reversible: false,
    tags: ["aesthetic", "dots", "decoration"],
  },
  {
    id: "sparkles-between",
    name: "Sparkles Between",
    description: "S✨p✨a✨r✨k✨l✨e between chars",
    emoji: "✨",
    category: "aesthetic",
    encode: encoders.encodeSparklesBetween,
    reversible: false,
    tags: ["aesthetic", "sparkles", "decoration"],
  },
  {
    id: "double-space",
    name: "Double Spaced",
    description: "D o u b l e spaced text",
    emoji: "📐",
    category: "aesthetic",
    encode: encoders.encodeDoubleSpace,
    reversible: false,
    tags: ["aesthetic", "space", "wide"],
  },
  {
    id: "underscore-between",
    name: "Underscore Between",
    description: "U_n_d_e_r_s_c_o_r_e style",
    emoji: "➖",
    category: "aesthetic",
    encode: encoders.encodeUnderscoreBetween,
    reversible: false,
    tags: ["aesthetic", "underscore", "decoration"],
  },
  {
    id: "bracketed",
    name: "[B][r][a][c][k][e][t][e][d]",
    description: "Brackets around each char",
    emoji: "🔲",
    category: "aesthetic",
    encode: encoders.encodeBracketed,
    reversible: false,
    tags: ["aesthetic", "brackets", "decoration"],
  },
  {
    id: "parenthesized-chars",
    name: "(P)(a)(r)(e)(n)(s)",
    description: "Parentheses around each char",
    emoji: "🔵",
    category: "aesthetic",
    encode: encoders.encodeParensWrapped,
    reversible: false,
    tags: ["aesthetic", "parentheses", "decoration"],
  },
  {
    id: "angle-bracketed",
    name: "<A><n><g><l><e>",
    description: "Angle brackets around each",
    emoji: "📐",
    category: "aesthetic",
    encode: encoders.encodeAngleBracketed,
    reversible: false,
    tags: ["aesthetic", "angle", "brackets"],
  },
  {
    id: "curly-bracketed",
    name: "{C}{u}{r}{l}{y}",
    description: "Curly braces around each",
    emoji: "🔶",
    category: "aesthetic",
    encode: encoders.encodeCurlyBracketed,
    reversible: false,
    tags: ["aesthetic", "curly", "braces"],
  },
  {
    id: "title-case",
    name: "Title Case",
    description: "Capitalize First Letter Of Each Word",
    emoji: "📝",
    category: "aesthetic",
    encode: encoders.encodeTitleCase,
    reversible: false,
    tags: ["aesthetic", "title", "case"],
  },
  {
    id: "alternating-word-case",
    name: "Alternating Word Case",
    description: "ALTERNATING word CASE",
    emoji: "🔀",
    category: "aesthetic",
    encode: encoders.encodeAlternatingWordCase,
    reversible: false,
    tags: ["aesthetic", "alternating", "case"],
  },
  {
    id: "inverted-title",
    name: "Inverted Title",
    description: "iNVERTED tITLE cASE",
    emoji: "🔃",
    category: "aesthetic",
    encode: encoders.encodeInvertedTitleCase,
    reversible: false,
    tags: ["aesthetic", "inverted", "case"],
  },
  {
    id: "sentence-case",
    name: "Sentence Case",
    description: "Sentence case format",
    emoji: "📜",
    category: "aesthetic",
    encode: encoders.encodeSentenceCase,
    reversible: false,
    tags: ["aesthetic", "sentence", "case"],
  },
  {
    id: "toggle-case",
    name: "Toggle Case",
    description: "tOGGLE cASE",
    emoji: "🔁",
    category: "aesthetic",
    encode: encoders.encodeToggleCase,
    reversible: false,
    tags: ["aesthetic", "toggle", "case"],
  },
  {
    id: "block-letters",
    name: "Block Letters",
    description: "🇧🇱🇴🇨🇰 style letters",
    emoji: "🔤",
    category: "aesthetic",
    encode: encoders.encodeBlockLetters,
    reversible: false,
    tags: ["aesthetic", "block", "letters"],
  },
  {
    id: "shadow-effect",
    name: "Shadow Effect",
    description: "Text with shadow",
    emoji: "🌑",
    category: "aesthetic",
    encode: encoders.encodeShadowEffect,
    reversible: false,
    tags: ["aesthetic", "shadow", "effect"],
  },
  {
    id: "3d-effect",
    name: "3D Effect",
    description: "Text with 3D depth",
    emoji: "🎯",
    category: "aesthetic",
    encode: encoders.encode3DEffect,
    reversible: false,
    tags: ["aesthetic", "3d", "effect"],
  },
  {
    id: "glitch-effect",
    name: "Glitch Effect",
    description: "G̷l̸i̵t̶c̷h̸ text",
    emoji: "📺",
    category: "aesthetic",
    encode: encoders.encodeGlitchEffect,
    reversible: false,
    tags: ["aesthetic", "glitch", "effect"],
  },
  {
    id: "repeating-pattern",
    name: "Repeating Pattern",
    description: "Text · Text · Text",
    emoji: "🔁",
    category: "aesthetic",
    encode: encoders.encodeRepeatingPattern,
    reversible: false,
    tags: ["aesthetic", "repeat", "pattern"],
  },
  {
    id: "quote-marks",
    name: "Quote Marks",
    description: '"Quoted text"',
    emoji: "💬",
    category: "aesthetic",
    encode: encoders.encodeQuoteMark,
    reversible: false,
    tags: ["aesthetic", "quote", "marks"],
  },
  {
    id: "fancy-quotes",
    name: "Fancy Quotes",
    description: '"Fancy quotes"',
    emoji: "📖",
    category: "aesthetic",
    encode: encoders.encodeFancyQuotes,
    reversible: false,
    tags: ["aesthetic", "fancy", "quotes"],
  },
  {
    id: "guillemets",
    name: "Guillemets",
    description: "«French quotes»",
    emoji: "🇫🇷",
    category: "aesthetic",
    encode: encoders.encodeGuillemets,
    reversible: false,
    tags: ["aesthetic", "french", "guillemets"],
  },
  {
    id: "japanese-quotes",
    name: "Japanese Quotes",
    description: "「Japanese quotes」",
    emoji: "🇯🇵",
    category: "aesthetic",
    encode: encoders.encodeJapaneseQuotes,
    reversible: false,
    tags: ["aesthetic", "japanese", "quotes"],
  },
  {
    id: "parenthetical-wrap",
    name: "Parenthetical",
    description: "(Parenthetical text)",
    emoji: "🔵",
    category: "aesthetic",
    encode: encoders.encodeParenthetical,
    reversible: false,
    tags: ["aesthetic", "parenthetical", "wrap"],
  },
  {
    id: "aside-wrap",
    name: "Em Dash Aside",
    description: "— Aside text —",
    emoji: "➖",
    category: "aesthetic",
    encode: encoders.encodeAside,
    reversible: false,
    tags: ["aesthetic", "aside", "em-dash"],
  },
  {
    id: "ellipsis-wrap",
    name: "Ellipsis Wrap",
    description: "...trailing off...",
    emoji: "💭",
    category: "aesthetic",
    encode: encoders.encodeEllipsisWrap,
    reversible: false,
    tags: ["aesthetic", "ellipsis", "wrap"],
  },
  {
    id: "emphasis-markers",
    name: "Emphasis Markers",
    description: "***Emphasized***",
    emoji: "❗",
    category: "aesthetic",
    encode: encoders.encodeEmphasisMarkers,
    reversible: false,
    tags: ["aesthetic", "emphasis", "markdown"],
  },
  {
    id: "drop-cap",
    name: "Drop Cap",
    description: "『D』rop cap style",
    emoji: "📜",
    category: "aesthetic",
    encode: encoders.encodeDropCap,
    reversible: false,
    tags: ["aesthetic", "dropcap", "typography"],
  },
  {
    id: "word-wrapping",
    name: "Flower Wrapping",
    description: "✿Word✿ wrapped",
    emoji: "🌸",
    category: "aesthetic",
    encode: encoders.encodeWordWrapping,
    reversible: false,
    tags: ["aesthetic", "flower", "wrap"],
  },
  {
    id: "word-decoration",
    name: "Word Decoration",
    description: "❀Decorated❀ words",
    emoji: "🌺",
    category: "aesthetic",
    encode: encoders.encodeWordDecoration,
    reversible: false,
    tags: ["aesthetic", "decorated", "words"],
  },
  {
    id: "alternating-decorations",
    name: "Alternating Decorations",
    description: "★Word♥ ✦Another✿",
    emoji: "🎭",
    category: "aesthetic",
    encode: encoders.encodeAlternatingDecorations,
    reversible: false,
    tags: ["aesthetic", "alternating", "decorations"],
  },
];
