import * as encoders from "../encoders/index.js";

export const artisticEncoders = [
  {
    id: "blocks",
    name: "Block Art",
    description: "Geometric pattern encoding",
    emoji: "◼️",
    category: "artistic",
    encode: encoders.encodeBoxDrawing,
    reversible: false,
    tags: ["artistic", "geometric", "visual"],
  },
  {
    id: "musical",
    name: "Musical Notes",
    description: "Your text as a symphony",
    emoji: "🎵",
    category: "artistic",
    encode: encoders.encodeMusical,
    reversible: false,
    tags: ["artistic", "music", "creative"],
  },
  {
    id: "zalgo",
    name: "Zalgo Chaos",
    description: "Ḩ̷̛e̶͝ ̸̕c̷̀o̶̎m̸̂e̵̊s̶̄",
    emoji: "😈",
    category: "artistic",
    encode: encoders.encodeZalgo,
    reversible: false,
    hasSettings: true,
    tags: ["artistic", "horror", "chaos"],
  },
  {
    id: "colors",
    name: "Color Blocks",
    description: "Rainbow data encoding",
    emoji: "🌈",
    category: "artistic",
    encode: encoders.encodeColorBlocks,
    reversible: false,
    tags: ["artistic", "colors", "visual"],
  },
  {
    id: "runes",
    name: "Ancient Runes",
    description: "Elder Futhark mysticism",
    emoji: "⚔️",
    category: "artistic",
    encode: encoders.encodeRunes,
    reversible: false,
    tags: ["artistic", "ancient", "mystical"],
  },
  {
    id: "ascii-art",
    name: "ASCII Art Banner",
    description: "Retro text art style",
    emoji: "🎨",
    category: "artistic",
    encode: encoders.encodeAsciiArt,
    reversible: false,
    tags: ["artistic", "retro", "banner", "ascii"],
  },
  {
    id: "sonar-ping",
    name: "Sonar Ping",
    description: "Underwater sonar patterns",
    emoji: "🔊",
    category: "artistic",
    encode: encoders.encodeSonarPing,
    decode: encoders.decodeSonarPing,
    reversible: true,
    tags: ["artistic", "sonar", "underwater", "acoustic"],
  },
  {
    id: "kiln-firing",
    name: "Pottery Kiln Firing",
    description: "Ceramic firing schedules",
    emoji: "🏺",
    category: "artistic",
    encode: encoders.encodeKilnFiring,
    decode: encoders.decodeKilnFiring,
    reversible: true,
    tags: ["artistic", "pottery", "ceramics", "craft"],
  },
  {
    id: "stained-glass",
    name: "Stained Glass",
    description: "Glass panel patterns",
    emoji: "🪟",
    category: "artistic",
    encode: encoders.encodeStainedGlass,
    decode: encoders.decodeStainedGlass,
    reversible: true,
    tags: ["artistic", "glass", "windows", "medieval"],
  },
  {
    id: "tessellation",
    name: "Tessellation Pattern",
    description: "Tiling patterns and symmetry",
    emoji: "⬡",
    category: "artistic",
    encode: encoders.encodeTessellation,
    decode: encoders.decodeTessellation,
    reversible: true,
    tags: ["artistic", "tessellation", "geometric", "patterns"],
  },
];
