import * as encoders from "../encoders/index.js";

export const cipherEncoders = [
  {
    id: "caesar",
    name: "Caesar Cipher",
    description: "Shift alphabet by N positions",
    emoji: "🏛️",
    category: "cipher",
    encode: encoders.encodeCaesar,
    decode: encoders.decodeCaesar,
    reversible: true,
    hasSettings: true,
    paramsResolver: (p) => [p.caesar || 13],
    tags: ["cipher", "cryptography", "ancient"],
  },
  {
    id: "rot13",
    name: "ROT13",
    description: "Caesar cipher with 13-letter shift",
    emoji: "🔄",
    category: "cipher",
    encode: encoders.encodeROT13,
    decode: encoders.decodeROT13,
    reversible: true,
    tags: ["cipher", "cryptography", "simple"],
  },
  {
    id: "reverse",
    name: "Reverse Text",
    description: "Simply backwards",
    emoji: "↩️",
    category: "cipher",
    encode: encoders.encodeReverse,
    decode: encoders.decodeReverse,
    reversible: true,
    tags: ["cipher", "simple", "mirror"],
  },
  {
    id: "atbash",
    name: "Atbash Cipher",
    description: "Hebrew cipher - reverse alphabet (A=Z)",
    emoji: "🔀",
    category: "cipher",
    encode: encoders.encodeAtbash,
    decode: encoders.decodeAtbash,
    reversible: true,
    tags: ["cipher", "cryptography", "hebrew", "ancient"],
  },
  {
    id: "vigenere",
    name: "Vigenère Cipher",
    description: "Keyword-based polyalphabetic cipher",
    emoji: "🔐",
    category: "cipher",
    encode: encoders.encodeVigenere,
    decode: encoders.decodeVigenere,
    reversible: true,
    hasSettings: true,
    paramsResolver: (p) => [p.vigenere || "SECRET"],
    tags: ["cipher", "cryptography", "polyalphabetic"],
  },
  {
    id: "rail-fence",
    name: "Rail Fence Cipher",
    description: "Zigzag transposition cipher",
    emoji: "🚃",
    category: "cipher",
    encode: encoders.encodeRailFence,
    decode: encoders.decodeRailFence,
    reversible: true,
    hasSettings: true,
    paramsResolver: (p) => [p["rail-fence"] || 3],
    tags: ["cipher", "transposition", "zigzag"],
  },
  {
    id: "bacon",
    name: "Bacon's Cipher",
    description: "Binary cipher using A and B",
    emoji: "🥓",
    category: "cipher",
    encode: encoders.encodeBacon,
    decode: encoders.decodeBacon,
    reversible: true,
    tags: ["cipher", "binary", "steganography"],
  },
  {
    id: "affine",
    name: "Affine Cipher",
    description: "Mathematical substitution cipher",
    emoji: "📐",
    category: "cipher",
    encode: encoders.encodeAffine,
    decode: encoders.decodeAffine,
    reversible: true,
    hasSettings: true,
    paramsResolver: (p) => [p.affine?.a || 5, p.affine?.b || 8],
    tags: ["cipher", "mathematical", "substitution"],
  },
  {
    id: "rot47",
    name: "ROT47",
    description: "Extended ASCII rotation cipher",
    emoji: "🔄",
    category: "cipher",
    encode: encoders.encodeROT47,
    decode: encoders.decodeROT47,
    reversible: true,
    tags: ["cipher", "rotation", "ascii"],
  },
  {
    id: "substitution",
    name: "QWERTY Substitution",
    description: "QWERTY keyboard cipher",
    emoji: "⌨️",
    category: "cipher",
    encode: encoders.encodeSubstitution,
    decode: encoders.decodeSubstitution,
    reversible: true,
    tags: ["cipher", "keyboard", "substitution"],
  },
  {
    id: "beaufort",
    name: "Beaufort Cipher",
    description: "Symmetric Vigenère variant",
    emoji: "⚓",
    category: "cipher",
    encode: encoders.encodeBeaufort,
    decode: encoders.decodeBeaufort,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "polyalphabetic", "symmetric"],
  },
  {
    id: "playfair",
    name: "Playfair Cipher",
    description: "Keyword-based digraph cipher",
    emoji: "🎭",
    category: "cipher",
    encode: encoders.encodePlayfair,
    decode: encoders.decodePlayfair,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "playfair", "digraph"],
  },
  {
    id: "columnar",
    name: "Columnar Transposition",
    description: "Column-based rearrangement",
    emoji: "📊",
    category: "cipher",
    encode: encoders.encodeColumnar,
    decode: encoders.decodeColumnar,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "transposition", "columnar"],
  },
  {
    id: "scytale",
    name: "Scytale Cipher",
    description: "Ancient Spartan cylinder cipher",
    emoji: "📜",
    category: "cipher",
    encode: encoders.encodeScytale,
    decode: encoders.decodeScytale,
    reversible: true,
    hasSettings: true,
    paramsResolver: (p) => [p.scytale || 4],
    tags: ["cipher", "ancient", "spartan"],
  },
  {
    id: "autokey",
    name: "Autokey Cipher",
    description: "Self-keying Vigenère variant",
    emoji: "🗝️",
    category: "cipher",
    encode: encoders.encodeAutokey,
    decode: encoders.decodeAutokey,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "autokey", "vigenere"],
  },
  {
    id: "hill",
    name: "Hill Cipher",
    description: "Matrix-based encryption",
    emoji: "📐",
    category: "cipher",
    encode: encoders.encodeHill,
    decode: encoders.decodeHill,
    reversible: true,
    tags: ["cipher", "hill", "matrix"],
  },
  {
    id: "bifid",
    name: "Bifid Cipher",
    description: "Polybius-based fractionation",
    emoji: "🔺",
    category: "cipher",
    encode: encoders.encodeBifid,
    decode: encoders.decodeBifid,
    reversible: true,
    tags: ["cipher", "bifid", "polybius"],
  },
  {
    id: "rot-n",
    name: "ROT-N Cipher",
    description: "Caesar cipher with custom rotation (1-25)",
    emoji: "🔄",
    category: "cipher",
    encode: encoders.encodeROTN,
    decode: encoders.decodeROTN,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "rotation", "caesar", "settings"],
  },
  {
    id: "rot5",
    name: "ROT5 (Numbers)",
    description: "Rotate digits only (0-9)",
    emoji: "5️⃣",
    category: "cipher",
    encode: encoders.encodeROT5,
    decode: encoders.decodeROT5,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "rotation", "numbers", "settings"],
  },
  {
    id: "rot18",
    name: "ROT18",
    description: "Combined ROT13 + ROT5 for letters and numbers",
    emoji: "🔃",
    category: "cipher",
    encode: encoders.encodeROT18,
    decode: encoders.decodeROT18,
    reversible: true,
    tags: ["cipher", "rotation", "combined"],
  },
  {
    id: "tap-code-pro",
    name: "Tap Code Pro",
    description: "Prison knock cipher with symbol options",
    emoji: "👊",
    category: "cipher",
    encode: encoders.encodeTapCodeParam,
    decode: encoders.decodeTapCodeParam,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "tap", "symbols", "settings"],
  },
  {
    id: "keyword-cipher",
    name: "Keyword Cipher",
    description: "Substitution cipher with custom keyword",
    emoji: "🔑",
    category: "cipher",
    encode: encoders.encodeKeywordCipher,
    decode: encoders.decodeKeywordCipher,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "keyword", "substitution", "settings"],
  },
  {
    id: "running-key",
    name: "Running Key Cipher",
    description: "Uses a book or passage as the key",
    emoji: "📖",
    category: "cipher",
    encode: encoders.encodeRunningKey,
    decode: encoders.decodeRunningKey,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "running-key", "book", "settings"],
  },
  {
    id: "gronsfeld",
    name: "Gronsfeld Cipher",
    description: "Vigenère variant with numeric key",
    emoji: "🔢",
    category: "cipher",
    encode: encoders.encodeGronsfeld,
    decode: encoders.decodeGronsfeld,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "gronsfeld", "numeric", "settings"],
  },
  {
    id: "trithemius",
    name: "Trithemius Cipher",
    description: "Progressive shift cipher (tabula recta)",
    emoji: "📈",
    category: "cipher",
    encode: encoders.encodeTrithemius,
    decode: encoders.decodeTrithemius,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "trithemius", "progressive", "settings"],
  },
  {
    id: "porta",
    name: "Porta Cipher",
    description: "Reciprocal polyalphabetic cipher",
    emoji: "🚪",
    category: "cipher",
    encode: encoders.encodePorta,
    decode: encoders.decodePorta,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "porta", "polyalphabetic", "settings"],
  },
  {
    id: "nihilist",
    name: "Nihilist Cipher",
    description: "Russian nihilist movement cipher",
    emoji: "🇷🇺",
    category: "cipher",
    encode: encoders.encodeNihilist,
    decode: encoders.decodeNihilist,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "nihilist", "polybius", "settings"],
  },
  {
    id: "polybius-pro",
    name: "Polybius Pro",
    description: "Polybius square with 5x5 or 6x6 grid option",
    emoji: "⬜",
    category: "cipher",
    encode: encoders.encodePolybiusParam,
    decode: encoders.decodePolybiusParam,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "polybius", "grid", "settings"],
  },
  {
    id: "adfgvx",
    name: "ADFGVX Cipher",
    description: "WWI German field cipher",
    emoji: "⚔️",
    category: "cipher",
    encode: encoders.encodeADFGVX,
    decode: encoders.decodeADFGVX,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "adfgvx", "military", "settings"],
  },
  {
    id: "book-cipher",
    name: "Book Cipher",
    description: "Encode using word positions from text",
    emoji: "📚",
    category: "cipher",
    encode: encoders.encodeBookCipher,
    decode: encoders.decodeBookCipher,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "book", "position", "settings"],
  },
  {
    id: "double-transposition",
    name: "Double Transposition",
    description: "Two-pass columnar transposition",
    emoji: "🔀",
    category: "cipher",
    encode: encoders.encodeDoubleTransposition,
    decode: encoders.decodeDoubleTransposition,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "transposition", "double", "settings"],
  },
  {
    id: "four-square",
    name: "Four-Square Cipher",
    description: "Digraphic cipher with two keywords",
    emoji: "🔲",
    category: "cipher",
    encode: encoders.encodeFourSquare,
    decode: encoders.decodeFourSquare,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "four-square", "digraph", "settings"],
  },
  {
    id: "straddling-checkerboard",
    name: "Straddling Checkerboard",
    description: "Variable-length numeric cipher",
    emoji: "♟️",
    category: "cipher",
    encode: encoders.encodeStraddlingCheckerboard,
    decode: encoders.decodeStraddlingCheckerboard,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "checkerboard", "numeric", "settings"],
  },
  {
    id: "homophonic",
    name: "Homophonic Cipher",
    description: "Multiple codes per letter",
    emoji: "🎭",
    category: "cipher",
    encode: encoders.encodeHomophonic,
    decode: encoders.decodeHomophonic,
    reversible: true,
    hasSettings: true,
    tags: ["cipher", "homophonic", "substitution", "settings"],
  },
];
