import * as encoders from "../encoders/index.js";

export const computerEncoders = [
  {
    id: "hex",
    name: "Hexadecimal",
    description: "Base-16 number system",
    emoji: "🔢",
    category: "computer",
    encode: encoders.encodeHex,
    decode: encoders.decodeHex,
    reversible: true,
    tags: ["computer", "hexadecimal", "programming"],
  },
  {
    id: "base64",
    name: "Base64",
    description: "Standard encoding for data transfer",
    emoji: "📦",
    category: "computer",
    encode: encoders.encodeBase64,
    decode: encoders.decodeBase64,
    reversible: true,
    tags: ["computer", "encoding", "web"],
  },
  {
    id: "base32",
    name: "Base32",
    description: "RFC 4648 encoding",
    emoji: "📋",
    category: "computer",
    encode: encoders.encodeBase32,
    decode: encoders.decodeBase32,
    reversible: true,
    tags: ["computer", "base32", "encoding"],
  },
  {
    id: "octal",
    name: "Octal (Base-8)",
    description: "Octal number representation",
    emoji: "8️⃣",
    category: "computer",
    encode: encoders.encodeOctal,
    decode: encoders.decodeOctal,
    reversible: true,
    tags: ["computer", "octal", "base8"],
  },
  {
    id: "ascii85",
    name: "ASCII85 (Base85)",
    description: "Adobe-style Base85 encoding",
    emoji: "📄",
    category: "computer",
    encode: encoders.encodeAscii85,
    decode: encoders.decodeAscii85,
    reversible: true,
    tags: ["computer", "ascii85", "base85"],
  },
  {
    id: "quoted-printable",
    name: "Quoted-Printable",
    description: "Email-safe encoding",
    emoji: "📧",
    category: "computer",
    encode: encoders.encodeQuotedPrintable,
    decode: encoders.decodeQuotedPrintable,
    reversible: true,
    tags: ["computer", "email", "encoding"],
  },
  {
    id: "a1z26",
    name: "A1Z26 (1=A, 2=B)",
    description: "Letter to number substitution",
    emoji: "🔢",
    category: "computer",
    encode: encoders.encodeA1Z26,
    decode: encoders.decodeA1Z26,
    reversible: true,
    tags: ["computer", "simple", "numbers"],
  },
  {
    id: "brainfuck",
    name: "Brainfuck Code",
    description: "Esoteric programming language",
    emoji: "🤯",
    category: "computer",
    encode: encoders.encodeBrainfuck,
    decode: encoders.decodeBrainfuck,
    reversible: true,
    tags: ["computer", "esoteric", "programming"],
  },
  {
    id: "binary-pro",
    name: "Binary Pro",
    description: "Binary with customizable bit grouping",
    emoji: "🔢",
    category: "computer",
    encode: encoders.encodeBinaryParam,
    decode: encoders.decodeBinaryParam,
    reversible: true,
    hasSettings: true,
    tags: ["computer", "binary", "bits", "settings"],
  },
  {
    id: "http-status",
    name: "HTTP Status",
    description: "HTTP response status style",
    emoji: "🌐",
    category: "computer",
    encode: encoders.encodeHTTPStatus,
    reversible: false,
    tags: ["computer", "http", "status"],
  },
  {
    id: "log-entry",
    name: "Log Entry",
    description: "Application log format",
    emoji: "📝",
    category: "computer",
    encode: encoders.encodeLogEntry,
    reversible: false,
    tags: ["computer", "log", "debug"],
  },
  {
    id: "terminal-command",
    name: "Terminal Command",
    description: "Unix terminal style",
    emoji: "💻",
    category: "computer",
    encode: encoders.encodeTerminal,
    reversible: false,
    tags: ["computer", "terminal", "unix"],
  },
  {
    id: "file-path",
    name: "File Path",
    description: "Unix file path format",
    emoji: "📁",
    category: "computer",
    encode: encoders.encodeFilePath,
    reversible: false,
    tags: ["computer", "file", "path"],
  },
  {
    id: "unix-epoch",
    name: "Unix Epoch",
    description: "Unix timestamp format",
    emoji: "⏱️",
    category: "computer",
    encode: encoders.encodeUnixEpoch,
    reversible: false,
    tags: ["computer", "unix", "timestamp"],
  },
  {
    id: "iso-date",
    name: "ISO Date Sequence",
    description: "ISO 8601 date encoding",
    emoji: "📅",
    category: "computer",
    encode: encoders.encodeISODate,
    reversible: false,
    tags: ["computer", "iso", "date"],
  },
];
