import * as encoders from "../encoders/index.js";

export const cryptoEncoders = [
  {
    id: "bech32",
    name: "Bech32-style",
    description:
      "Bitcoin SegWit-inspired character mapping (not a real Bech32 implementation; no BCH checksum)",
    emoji: "₿",
    category: "crypto",
    encode: encoders.encodeBech32,
    decode: encoders.decodeBech32,
    reversible: true,
    tags: ["crypto", "bitcoin", "blockchain", "base32"],
  },
  {
    id: "z-base32",
    name: "Z-Base-32-style",
    description:
      "Z-Base-32-inspired character mapping (not RFC-compliant bitstream packing)",
    emoji: "🔢",
    category: "crypto",
    encode: encoders.encodeZBase32,
    decode: encoders.decodeZBase32,
    reversible: true,
    tags: ["crypto", "encoding", "base32", "zooko"],
  },
  {
    id: "crockford-base32",
    name: "Crockford Base32",
    description: "Human-friendly base-32 encoding",
    emoji: "🔣",
    category: "crypto",
    encode: encoders.encodeCrockfordBase32,
    decode: encoders.decodeCrockfordBase32,
    reversible: true,
    tags: ["crypto", "encoding", "base32", "crockford"],
  },
  {
    id: "sha256-style",
    name: "SHA-256 Style",
    description: "Cryptographic hash representation",
    emoji: "🔐",
    category: "crypto",
    encode: encoders.encodeSHA256Style,
    tags: ["crypto", "hash", "sha256", "fingerprint"],
  },
  {
    id: "argon2-style",
    name: "Argon2 Format",
    description: "Modern password hash format",
    emoji: "🛡️",
    category: "crypto",
    encode: encoders.encodeArgon2Style,
    tags: ["crypto", "password", "argon2", "hashing"],
  },
  {
    id: "bcrypt-style",
    name: "BCrypt Format",
    description: "Password hashing format",
    emoji: "🔑",
    category: "crypto",
    encode: encoders.encodeBCryptStyle,
    tags: ["crypto", "password", "bcrypt", "hashing"],
  },
  {
    id: "pem-style",
    name: "PEM Key Format",
    description: "RSA private key representation",
    emoji: "🔐",
    category: "crypto",
    encode: encoders.encodePEMStyle,
    tags: ["crypto", "keys", "pem", "rsa"],
  },
  {
    id: "ssh-key-style",
    name: "SSH Public Key",
    description: "SSH key format",
    emoji: "🔑",
    category: "crypto",
    encode: encoders.encodeSSHKeyStyle,
    tags: ["crypto", "ssh", "keys", "authentication"],
  },
  {
    id: "totp",
    name: "TOTP (2FA)",
    description: "Time-based one-time password",
    emoji: "⏱️",
    category: "crypto",
    encode: encoders.encodeTOTP,
    decode: encoders.decodeTOTP,
    reversible: true,
    tags: ["crypto", "totp", "2fa", "authentication"],
  },
  {
    id: "api-key",
    name: "API Key Format",
    description: "Modern API authentication keys",
    emoji: "🔑",
    category: "crypto",
    encode: encoders.encodeAPIKey,
    tags: ["crypto", "api", "keys", "authentication"],
  },
  {
    id: "ulid",
    name: "ULID",
    description: "Sortable unique identifiers",
    emoji: "🆔",
    category: "crypto",
    encode: encoders.encodeULID,
    decode: encoders.decodeULID,
    reversible: false,
    tags: ["crypto", "ulid", "uuid", "identifiers"],
  },
  {
    id: "snowflake",
    name: "Snowflake ID",
    description: "Twitter/Discord distributed IDs",
    emoji: "❄️",
    category: "crypto",
    encode: encoders.encodeSnowflake,
    decode: encoders.decodeSnowflake,
    reversible: false,
    tags: ["crypto", "snowflake", "distributed", "ids"],
  },
  {
    id: "x509-serial",
    name: "X.509 Serial Number",
    description: "Certificate serial numbers",
    emoji: "📜",
    category: "crypto",
    encode: encoders.encodeX509Serial,
    decode: encoders.decodeX509Serial,
    reversible: false,
    tags: ["crypto", "x509", "certificates", "pki"],
  },
  {
    id: "ethereum-address",
    name: "Ethereum Address",
    description: "Ethereum wallet addresses",
    emoji: "⟠",
    category: "crypto",
    encode: encoders.encodeEthereumAddress,
    tags: ["crypto", "ethereum", "blockchain", "cryptocurrency"],
  },
  {
    id: "bitcoin-address",
    name: "Bitcoin Address",
    description: "Bitcoin wallet addresses (Base58)",
    emoji: "₿",
    category: "crypto",
    encode: encoders.encodeBitcoinAddress,
    tags: ["crypto", "bitcoin", "blockchain", "cryptocurrency"],
  },
  {
    id: "crypto-strength",
    name: "Crypto Strength Indicator",
    description: "Encryption algorithm strength",
    emoji: "🔒",
    category: "crypto",
    encode: encoders.encodeWithStrength,
    tags: ["crypto", "encryption", "strength", "security"],
  },
  {
    id: "multibase",
    name: "Multibase",
    description: "Self-describing base encoding (IPFS)",
    emoji: "🌐",
    category: "crypto",
    encode: encoders.encodeMultibase,
    decode: encoders.decodeMultibase,
    reversible: false,
    tags: ["crypto", "multibase", "ipfs", "multiformats"],
  },
];
