import * as encoders from "../encoders/index.js";

export const forensicsEncoders = [
  {
    id: "timestamp",
    name: "Unix Timestamp",
    description: "Encode as Unix timestamps",
    emoji: "⏰",
    category: "forensics",
    encode: encoders.encodeTimestamp,
    decode: encoders.decodeTimestamp,
    reversible: true,
    tags: ["forensics", "timestamp", "time"],
  },
  {
    id: "mac-address",
    name: "MAC Address Format",
    description: "Network MAC address style",
    emoji: "🔌",
    category: "forensics",
    encode: encoders.encodeMACAddress,
    reversible: false,
    tags: ["forensics", "network", "mac"],
  },
  {
    id: "ip-address",
    name: "IP Address Format",
    description: "IPv4 address encoding",
    emoji: "🌐",
    category: "forensics",
    encode: encoders.encodeIPAddress,
    reversible: false,
    tags: ["forensics", "network", "ip"],
  },
  {
    id: "uuid",
    name: "UUID Style",
    description: "Universally unique identifier",
    emoji: "🆔",
    category: "forensics",
    encode: encoders.encodeUUID,
    reversible: false,
    tags: ["forensics", "uuid", "identifier"],
  },
  {
    id: "visual-hash",
    name: "Visual Hash",
    description: "Graphical hash pattern",
    emoji: "#️⃣",
    category: "forensics",
    encode: encoders.encodeVisualHash,
    reversible: false,
    tags: ["forensics", "hash", "visual"],
  },
  {
    id: "magic-bytes",
    name: "Magic Bytes",
    description: "File signature headers",
    emoji: "✨",
    category: "forensics",
    encode: encoders.encodeMagicBytes,
    reversible: false,
    tags: ["forensics", "magic", "file-header"],
  },
  {
    id: "registry",
    name: "Registry Path",
    description: "Windows registry format",
    emoji: "📁",
    category: "forensics",
    encode: encoders.encodeRegistryPath,
    reversible: false,
    tags: ["forensics", "registry", "windows"],
  },
  {
    id: "hex-dump",
    name: "Hex Dump",
    description: "Forensic hex dump format",
    emoji: "🔬",
    category: "forensics",
    encode: encoders.encodeHexDump,
    reversible: false,
    tags: ["forensics", "hexdump", "analysis"],
  },
  {
    id: "base58",
    name: "Base58 (Bitcoin)",
    description: "Bitcoin-style Base58",
    emoji: "₿",
    category: "forensics",
    encode: encoders.encodeBase58,
    decode: encoders.decodeBase58,
    reversible: true,
    tags: ["forensics", "base58", "bitcoin"],
  },
  {
    id: "homoglyph",
    name: "Homoglyph Steganography",
    description: "Similar-looking characters",
    emoji: "👀",
    category: "forensics",
    encode: encoders.encodeHomoglyph,
    decode: encoders.decodeHomoglyph,
    reversible: true,
    tags: ["forensics", "steganography", "homoglyph"],
  },
  {
    id: "unicode-tag",
    name: "Unicode Tag Steganography",
    description: "Invisible Unicode tags",
    emoji: "🏷️",
    category: "forensics",
    encode: encoders.encodeUnicodeTag,
    decode: encoders.decodeUnicodeTag,
    reversible: true,
    tags: ["forensics", "steganography", "invisible"],
  },
  {
    id: "variation-selector",
    name: "Variation Selector",
    description: "Unicode variation steganography",
    emoji: "🌟",
    category: "forensics",
    encode: encoders.encodeVariationSelector,
    reversible: false,
    tags: ["forensics", "steganography", "unicode"],
  },
  {
    id: "metadata",
    name: "Metadata Format",
    description: "EXIF-like metadata tags",
    emoji: "📋",
    category: "forensics",
    encode: encoders.encodeMetadata,
    reversible: false,
    tags: ["forensics", "metadata", "exif"],
  },
  {
    id: "null-byte",
    name: "Null Byte Pattern",
    description: "Null byte injection style",
    emoji: "∅",
    category: "forensics",
    encode: encoders.encodeNullByte,
    decode: encoders.decodeNullByte,
    reversible: true,
    tags: ["forensics", "null", "security"],
  },
  {
    id: "certificate",
    name: "Certificate Format",
    description: "PEM certificate style",
    emoji: "🔏",
    category: "forensics",
    encode: encoders.encodeCertificate,
    reversible: false,
    tags: ["forensics", "certificate", "ssl"],
  },
  {
    id: "dns-txt",
    name: "DNS TXT Record",
    description: "DNS record format",
    emoji: "📡",
    category: "forensics",
    encode: encoders.encodeDNSTXT,
    reversible: false,
    tags: ["forensics", "dns", "record"],
  },
  {
    id: "jwt-style",
    name: "JWT Style",
    description: "JSON Web Token format",
    emoji: "🎫",
    category: "forensics",
    encode: encoders.encodeJWTStyle,
    decode: encoders.decodeJWTStyle,
    reversible: true,
    tags: ["forensics", "jwt", "token"],
  },
  {
    id: "http-header",
    name: "HTTP Headers",
    description: "HTTP header format",
    emoji: "📨",
    category: "forensics",
    encode: encoders.encodeHTTPHeader,
    reversible: false,
    tags: ["forensics", "http", "headers"],
  },
  {
    id: "sql-escape",
    name: "SQL CHAR Encoding",
    description: "SQL character encoding",
    emoji: "💾",
    category: "forensics",
    encode: encoders.encodeSQLEscape,
    reversible: false,
    tags: ["forensics", "sql", "database"],
  },
  {
    id: "regex-pattern",
    name: "Regex Escape",
    description: "Regular expression encoding",
    emoji: "🔍",
    category: "forensics",
    encode: encoders.encodeRegexPattern,
    decode: encoders.decodeRegexPattern,
    reversible: true,
    tags: ["forensics", "regex", "pattern"],
  },
  {
    id: "assembly",
    name: "Assembly MOV",
    description: "x86 assembly style",
    emoji: "⚙️",
    category: "forensics",
    encode: encoders.encodeAssembly,
    reversible: false,
    tags: ["forensics", "assembly", "low-level"],
  },
  {
    id: "pgp-style",
    name: "PGP Message",
    description: "PGP encrypted message style",
    emoji: "🔐",
    category: "forensics",
    encode: encoders.encodePGPStyle,
    reversible: false,
    tags: ["forensics", "pgp", "encrypted"],
  },
  {
    id: "encrypted-placeholder",
    name: "Encrypted Display",
    description: "Encrypted message placeholder",
    emoji: "🔒",
    category: "forensics",
    encode: encoders.encodeEncryptedPlaceholder,
    reversible: false,
    tags: ["forensics", "encrypted", "placeholder"],
  },
];
