import * as encoders from "../encoders/index.js";

export const funEncoders = [
  {
    id: "emoji",
    name: "Emoji Encoding",
    description: "Express text through emoji pairs",
    emoji: "😎",
    category: "fun",
    encode: encoders.encodeEmoji,
    decode: encoders.decodeEmoji,
    reversible: true,
    tags: ["fun", "emoji", "creative"],
  },
  {
    id: "bubble",
    name: "Bubble Text",
    description: "Cute circled characters",
    emoji: "⭕",
    category: "fun",
    encode: encoders.encodeBubble,
    reversible: false,
    tags: ["fun", "aesthetic", "social"],
  },
  {
    id: "upside-down",
    name: "Upside Down",
    description: "Australian mode activated",
    emoji: "🙃",
    category: "fun",
    encode: encoders.encodeUpsideDown,
    reversible: false,
    tags: ["fun", "flip", "creative"],
  },
  {
    id: "pig-latin",
    name: "Pig Latin",
    description: "Ixnay on the ormalfay",
    emoji: "🐷",
    category: "fun",
    encode: encoders.encodePigLatin,
    reversible: false,
    tags: ["fun", "language", "playground"],
  },
  {
    id: "wingdings",
    name: "Wingdings",
    description: "Symbol font encoding",
    emoji: "✡",
    category: "fun",
    encode: encoders.encodeWingdings,
    reversible: false,
    tags: ["fun", "symbols", "font"],
  },
  {
    id: "semaphore",
    name: "Semaphore Flags",
    description: "Maritime flag signals",
    emoji: "🚩",
    category: "fun",
    encode: encoders.encodeSemaphore,
    reversible: false,
    tags: ["fun", "flags", "maritime"],
  },
  {
    id: "morse-emoji",
    name: "Morse Emoji",
    description: "Morse code with visual dots",
    emoji: "⚫",
    category: "fun",
    encode: encoders.encodeMorseEmoji,
    reversible: false,
    tags: ["fun", "morse", "visual"],
  },
  {
    id: "tiny",
    name: "ᵀⁱⁿʸ ᵀᵉˣᵗ",
    description: "Superscript tiny text",
    emoji: "🔬",
    category: "fun",
    encode: encoders.encodeTinyText,
    reversible: false,
    tags: ["fun", "tiny", "superscript"],
  },
  {
    id: "strikethrough",
    name: "S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶",
    description: "Crossed out text",
    emoji: "✖️",
    category: "fun",
    encode: encoders.encodeStrikethrough,
    reversible: false,
    tags: ["fun", "strikethrough", "text-effect"],
  },
  {
    id: "underline",
    name: "U̲n̲d̲e̲r̲l̲i̲n̲e̲",
    description: "Underlined text",
    emoji: "📏",
    category: "fun",
    encode: encoders.encodeUnderline,
    reversible: false,
    tags: ["fun", "underline", "text-effect"],
  },
  {
    id: "redacted",
    name: "R██ac██d T██t",
    description: "Randomly redacted text",
    emoji: "⬛",
    category: "fun",
    encode: encoders.encodeRedacted,
    reversible: false,
    hasSettings: true,
    tags: ["fun", "redacted", "secret"],
  },
  {
    id: "keyboard-shift",
    name: "Keyboard Shift",
    description: "Shift keys right on keyboard",
    emoji: "⌨️",
    category: "fun",
    encode: encoders.encodeKeyboardShift,
    decode: encoders.decodeKeyboardShift,
    reversible: true,
    tags: ["fun", "keyboard", "shift"],
  },
  {
    id: "tally",
    name: "Tally Marks",
    description: "Counting tally marks",
    emoji: "𝍡",
    category: "fun",
    encode: encoders.encodeTally,
    reversible: false,
    tags: ["fun", "tally", "counting"],
  },
  {
    id: "acrostic",
    name: "Acrostic Generator",
    description: "First letters spell message",
    emoji: "📝",
    category: "fun",
    encode: encoders.encodeAcrostic,
    reversible: false,
    tags: ["fun", "acrostic", "poem"],
  },
  {
    id: "leetspeak-pro",
    name: "Leetspeak Pro",
    description: "H4ck3r sp34k with intensity control",
    emoji: "💻",
    category: "fun",
    encode: encoders.encodeLeetspeakParam,
    reversible: false,
    hasSettings: true,
    tags: ["fun", "hacker", "leetspeak", "settings"],
  },
  {
    id: "uwu-pro",
    name: "UwU Pro",
    description: "Cutesy speak with customizable intensity OwO",
    emoji: "🥺",
    category: "fun",
    encode: encoders.encodeUwUParam,
    reversible: false,
    hasSettings: true,
    tags: ["fun", "cute", "uwu", "settings"],
  },
  {
    id: "spongebob-pro",
    name: "SpOnGeBoB Pro",
    description: "mOcKiNg TeXt with randomness control",
    emoji: "🧽",
    category: "fun",
    encode: encoders.encodeSpongebobParam,
    reversible: false,
    hasSettings: true,
    tags: ["fun", "meme", "spongebob", "settings"],
  },
  {
    id: "emojipasta-pro",
    name: "Emojipasta Pro 😂🔥",
    description: "Add emojis with density control 💯",
    emoji: "😫",
    category: "fun",
    encode: encoders.encodeEmojipastaParam,
    reversible: false,
    hasSettings: true,
    tags: ["fun", "emoji", "pasta", "settings"],
  },
  {
    id: "fruit-emoji",
    name: "Fruit Encoding",
    description: "Encode with fruit emojis",
    emoji: "🍎",
    category: "fun",
    encode: encoders.encodeFruitEmoji,
    reversible: false,
    tags: ["fun", "fruit", "emoji"],
  },
  {
    id: "face-emoji",
    name: "Face Encoding",
    description: "Encode with face emojis",
    emoji: "😀",
    category: "fun",
    encode: encoders.encodeFaceEmoji,
    reversible: false,
    tags: ["fun", "face", "emoji"],
  },
  {
    id: "hand-emoji",
    name: "Hand Encoding",
    description: "Encode with hand emojis",
    emoji: "👋",
    category: "fun",
    encode: encoders.encodeHandEmoji,
    reversible: false,
    tags: ["fun", "hand", "emoji"],
  },
  {
    id: "heart-emoji",
    name: "Heart Encoding",
    description: "Encode with heart emojis",
    emoji: "❤️",
    category: "fun",
    encode: encoders.encodeHeartEmoji,
    reversible: false,
    tags: ["fun", "heart", "emoji"],
  },
  {
    id: "nature-emoji",
    name: "Nature Encoding",
    description: "Encode with nature emojis",
    emoji: "🌸",
    category: "fun",
    encode: encoders.encodeNatureEmoji,
    reversible: false,
    tags: ["fun", "nature", "emoji"],
  },
  {
    id: "transport-emoji",
    name: "Transport Encoding",
    description: "Encode with transport emojis",
    emoji: "🚗",
    category: "fun",
    encode: encoders.encodeTransportEmoji,
    reversible: false,
    tags: ["fun", "transport", "emoji"],
  },
  {
    id: "building-emoji",
    name: "Building Encoding",
    description: "Encode with building emojis",
    emoji: "🏠",
    category: "fun",
    encode: encoders.encodeBuildingEmoji,
    reversible: false,
    tags: ["fun", "building", "emoji"],
  },
  {
    id: "tool-emoji",
    name: "Tool Encoding",
    description: "Encode with tool emojis",
    emoji: "🔧",
    category: "fun",
    encode: encoders.encodeToolEmoji,
    reversible: false,
    tags: ["fun", "tool", "emoji"],
  },
  {
    id: "news-ticker",
    name: "News Ticker",
    description: "Breaking news ticker style",
    emoji: "📺",
    category: "fun",
    encode: encoders.encodeNewsTicker,
    reversible: false,
    tags: ["fun", "news", "ticker"],
  },
  {
    id: "emergency-broadcast",
    name: "Emergency Broadcast",
    description: "Emergency alert style",
    emoji: "🚨",
    category: "fun",
    encode: encoders.encodeEmergencyBroadcast,
    reversible: false,
    tags: ["fun", "emergency", "alert"],
  },
  {
    id: "headline",
    name: "News Headline",
    description: "News headline format",
    emoji: "📰",
    category: "fun",
    encode: encoders.encodeHeadline,
    reversible: false,
    tags: ["fun", "news", "headline"],
  },
  {
    id: "random-case",
    name: "Random Case",
    description: "rAnDoM cAsE",
    emoji: "🎲",
    category: "fun",
    encode: encoders.encodeRandomCase,
    reversible: false,
    tags: ["fun", "random", "case"],
  },
  {
    id: "word-reversal",
    name: "Word Reversal",
    description: "droW lasreveR",
    emoji: "↩️",
    category: "fun",
    encode: encoders.encodeWordReversal,
    reversible: false,
    tags: ["fun", "word", "reverse"],
  },
  {
    id: "word-order-reversal",
    name: "Word Order Reversal",
    description: "Reversal Order Word",
    emoji: "🔄",
    category: "fun",
    encode: encoders.encodeWordOrderReversal,
    reversible: false,
    tags: ["fun", "order", "reverse"],
  },
  {
    id: "mirrored-text",
    name: "Mirrored Text",
    description: "Text | txeT",
    emoji: "🪞",
    category: "fun",
    encode: encoders.encodeMirroredText,
    reversible: false,
    tags: ["fun", "mirror", "text"],
  },
  {
    id: "action-asterisks",
    name: "Action Asterisks",
    description: "*does action*",
    emoji: "⭐",
    category: "fun",
    encode: encoders.encodeActionAsterisks,
    reversible: false,
    tags: ["fun", "action", "roleplay"],
  },
];
