import * as encoders from "../encoders/index.js";

export const gamesEncoders = [
  {
    id: "tetris",
    name: "Tetris Blocks",
    description: "Tetromino encoding",
    emoji: "🟦",
    category: "games",
    encode: encoders.encodeTetris,
    reversible: false,
    tags: ["games", "tetris", "puzzle"],
  },
  {
    id: "poker-hand",
    name: "Poker Hand",
    description: "Playing card hands",
    emoji: "♠️",
    category: "games",
    encode: encoders.encodePokerHand,
    decode: encoders.decodePokerHand,
    reversible: true,
    tags: ["games", "poker", "cards"],
  },
  {
    id: "rpg-stats",
    name: "RPG Stats",
    description: "Character attributes",
    emoji: "⚔️",
    category: "games",
    encode: encoders.encodeRPGStats,
    reversible: false,
    tags: ["games", "rpg", "stats"],
  },
  {
    id: "level-xp",
    name: "Level/XP",
    description: "Experience points",
    emoji: "📊",
    category: "games",
    encode: encoders.encodeLevelXP,
    reversible: false,
    tags: ["games", "level", "xp"],
  },
  {
    id: "achievement-badge",
    name: "Achievement Badge",
    description: "Gaming achievements",
    emoji: "🏆",
    category: "games",
    encode: encoders.encodeAchievement,
    reversible: false,
    tags: ["games", "achievement", "badge"],
  },
  {
    id: "health-bar",
    name: "Health Bar",
    description: "HP bar visualization",
    emoji: "❤️",
    category: "games",
    encode: encoders.encodeHealthBar,
    reversible: false,
    tags: ["games", "health", "hp"],
  },
  {
    id: "slot-machine",
    name: "Slot Machine",
    description: "Casino slot symbols",
    emoji: "🎰",
    category: "games",
    encode: encoders.encodeSlotMachine,
    reversible: false,
    tags: ["games", "slot", "casino"],
  },
  {
    id: "crossword",
    name: "Crossword Clue",
    description: "Crossword puzzle format",
    emoji: "📝",
    category: "games",
    encode: encoders.encodeCrossword,
    reversible: false,
    tags: ["games", "crossword", "puzzle"],
  },
  {
    id: "sudoku",
    name: "Sudoku Grid",
    description: "Number puzzle grid",
    emoji: "🔢",
    category: "games",
    encode: encoders.encodeSudoku,
    reversible: false,
    tags: ["games", "sudoku", "puzzle"],
  },
  {
    id: "pacman",
    name: "Pacman Pattern",
    description: "Arcade game symbols",
    emoji: "ᗧ",
    category: "games",
    encode: encoders.encodePacman,
    reversible: false,
    tags: ["games", "pacman", "arcade"],
  },
  {
    id: "mario-block",
    name: "Mario Blocks",
    description: "Platform game blocks",
    emoji: "❓",
    category: "games",
    encode: encoders.encodeMarioBlock,
    reversible: false,
    tags: ["games", "mario", "platform"],
  },
  {
    id: "rubiks-cube",
    name: "Rubik's Cube Moves",
    description: "Cube notation",
    emoji: "🟩",
    category: "games",
    encode: encoders.encodeRubiksCube,
    decode: encoders.decodeRubiksCube,
    reversible: true,
    tags: ["games", "rubiks", "puzzle"],
  },
  {
    id: "dungeon-map",
    name: "Dungeon Map",
    description: "Roguelike map symbols",
    emoji: "🗺️",
    category: "games",
    encode: encoders.encodeDungeonMap,
    reversible: false,
    tags: ["games", "dungeon", "rpg"],
  },
  {
    id: "pokemon-type",
    name: "Pokemon Types",
    description: "Element type encoding",
    emoji: "🔥",
    category: "games",
    encode: encoders.encodePokemonType,
    reversible: false,
    tags: ["games", "pokemon", "type"],
  },
  {
    id: "trading-card",
    name: "Trading Card",
    description: "CCG card format",
    emoji: "🃏",
    category: "games",
    encode: encoders.encodeTradingCard,
    reversible: false,
    tags: ["games", "card", "trading"],
  },
  {
    id: "scoreboard",
    name: "Scoreboard",
    description: "Game score display",
    emoji: "🏅",
    category: "games",
    encode: encoders.encodeScoreboard,
    reversible: false,
    tags: ["games", "score", "rank"],
  },
  {
    id: "controller-input",
    name: "Controller Input",
    description: "Button press sequence",
    emoji: "🎮",
    category: "games",
    encode: encoders.encodeControllerInput,
    reversible: false,
    tags: ["games", "controller", "input"],
  },
  {
    id: "inventory",
    name: "Inventory Slot",
    description: "Game item inventory",
    emoji: "🎒",
    category: "games",
    encode: encoders.encodeInventory,
    reversible: false,
    tags: ["games", "inventory", "items"],
  },
  {
    id: "quest-log",
    name: "Quest Log",
    description: "Quest tracker format",
    emoji: "📜",
    category: "games",
    encode: encoders.encodeQuestLog,
    reversible: false,
    tags: ["games", "quest", "rpg"],
  },
  {
    id: "skill-tree",
    name: "Skill Tree",
    description: "Ability progression",
    emoji: "🌟",
    category: "games",
    encode: encoders.encodeSkillTree,
    reversible: false,
    tags: ["games", "skill", "rpg"],
  },
  {
    id: "mini-map",
    name: "Mini Map",
    description: "Miniature map grid",
    emoji: "🗺️",
    category: "games",
    encode: encoders.encodeMiniMap,
    reversible: false,
    tags: ["games", "map", "navigation"],
  },
  {
    id: "combo-move",
    name: "Combo Move",
    description: "Fighting game combo",
    emoji: "💥",
    category: "games",
    encode: encoders.encodeComboMove,
    reversible: false,
    tags: ["games", "combo", "fighting"],
  },
  {
    id: "leaderboard",
    name: "Leaderboard",
    description: "High score rankings",
    emoji: "🥇",
    category: "games",
    encode: encoders.encodeLeaderboard,
    reversible: false,
    tags: ["games", "leaderboard", "rank"],
  },
  {
    id: "game-chat",
    name: "Game Chat",
    description: "Twitch/game chat style",
    emoji: "🎮",
    category: "games",
    encode: encoders.encodeGameChat,
    reversible: false,
    tags: ["games", "chat", "twitch"],
  },
  {
    id: "mmo-loot",
    name: "MMO Loot",
    description: "MMORPG item rarity format",
    emoji: "⚔️",
    category: "games",
    encode: encoders.encodeMMOLoot,
    reversible: false,
    tags: ["games", "mmo", "loot"],
  },
  {
    id: "dice-notation",
    name: "D&D Dice Notation",
    description: "Tabletop RPG dice format",
    emoji: "🎲",
    category: "games",
    encode: encoders.encodeDiceNotation,
    reversible: false,
    tags: ["games", "dnd", "dice"],
  },
];
