import * as encoders from "../encoders/index.js";

export const linguisticEncoders = [
  {
    id: "greek",
    name: "Greek Alphabet",
    description: "Transliterate to Greek letters",
    emoji: "Ω",
    category: "linguistic",
    encode: encoders.encodeGreek,
    decode: encoders.decodeGreek,
    reversible: true,
    tags: ["linguistic", "greek", "alphabet"],
  },
  {
    id: "cyrillic",
    name: "Cyrillic Script",
    description: "Transliterate to Cyrillic letters",
    emoji: "Д",
    category: "linguistic",
    encode: encoders.encodeCyrillic,
    decode: encoders.decodeCyrillic,
    reversible: true,
    tags: ["linguistic", "cyrillic", "russian"],
  },
  {
    id: "hebrew",
    name: "Hebrew Alephbet",
    description: "Transliterate to Hebrew letters",
    emoji: "א",
    category: "linguistic",
    encode: encoders.encodeHebrew,
    decode: encoders.decodeHebrew,
    reversible: true,
    tags: ["linguistic", "hebrew", "ancient"],
  },
  {
    id: "korean",
    name: "Korean Hangul",
    description: "Map to Korean syllables",
    emoji: "한",
    category: "linguistic",
    encode: encoders.encodeKorean,
    decode: encoders.decodeKorean,
    reversible: true,
    tags: ["linguistic", "korean", "hangul"],
  },
  {
    id: "phonetic-ipa",
    name: "IPA Transcription",
    description: "International Phonetic Alphabet",
    emoji: "🗣️",
    category: "linguistic",
    encode: encoders.encodeIPA,
    reversible: false,
    tags: ["linguistic", "phonetic", "pronunciation"],
  },
  {
    id: "hiragana",
    name: "Hiragana Style",
    description: "Japanese hiragana characters",
    emoji: "🇯🇵",
    category: "linguistic",
    encode: encoders.encodeHiragana,
    reversible: false,
    tags: ["linguistic", "japanese", "hiragana"],
  },
  {
    id: "katakana",
    name: "Katakana Style",
    description: "Japanese katakana characters",
    emoji: "🗾",
    category: "linguistic",
    encode: encoders.encodeKatakana,
    reversible: false,
    tags: ["linguistic", "japanese", "katakana"],
  },
  {
    id: "arabic-style",
    name: "Arabic Style",
    description: "Arabic-style letters",
    emoji: "🕌",
    category: "linguistic",
    encode: encoders.encodeArabicStyle,
    reversible: false,
    tags: ["linguistic", "arabic", "middle-east"],
  },
  {
    id: "thai-style",
    name: "Thai Style",
    description: "Thai alphabet encoding",
    emoji: "🇹🇭",
    category: "linguistic",
    encode: encoders.encodeThaiStyle,
    reversible: false,
    tags: ["linguistic", "thai", "southeast-asia"],
  },
  {
    id: "devanagari",
    name: "Devanagari (Hindi)",
    description: "Hindi/Sanskrit script",
    emoji: "🇮🇳",
    category: "linguistic",
    encode: encoders.encodeDevanagari,
    reversible: false,
    tags: ["linguistic", "hindi", "devanagari"],
  },
  {
    id: "bengali-style",
    name: "Bengali Style",
    description: "Bengali script encoding",
    emoji: "🇧🇩",
    category: "linguistic",
    encode: encoders.encodeBengali,
    reversible: false,
    tags: ["linguistic", "bengali", "south-asia"],
  },
  {
    id: "tamil-style",
    name: "Tamil Style",
    description: "Tamil script encoding",
    emoji: "🏛️",
    category: "linguistic",
    encode: encoders.encodeTamil,
    reversible: false,
    tags: ["linguistic", "tamil", "south-asia"],
  },
  {
    id: "telugu-style",
    name: "Telugu Style",
    description: "Telugu script encoding",
    emoji: "📜",
    category: "linguistic",
    encode: encoders.encodeTelugu,
    reversible: false,
    tags: ["linguistic", "telugu", "south-asia"],
  },
  {
    id: "kannada-style",
    name: "Kannada Style",
    description: "Kannada script encoding",
    emoji: "📝",
    category: "linguistic",
    encode: encoders.encodeKannada,
    reversible: false,
    tags: ["linguistic", "kannada", "south-asia"],
  },
  {
    id: "malayalam-style",
    name: "Malayalam Style",
    description: "Malayalam script encoding",
    emoji: "🌴",
    category: "linguistic",
    encode: encoders.encodeMalayalam,
    reversible: false,
    tags: ["linguistic", "malayalam", "south-asia"],
  },
  {
    id: "gujarati-style",
    name: "Gujarati Style",
    description: "Gujarati script encoding",
    emoji: "🦁",
    category: "linguistic",
    encode: encoders.encodeGujarati,
    reversible: false,
    tags: ["linguistic", "gujarati", "south-asia"],
  },
  {
    id: "punjabi-style",
    name: "Punjabi (Gurmukhi)",
    description: "Gurmukhi script encoding",
    emoji: "🪷",
    category: "linguistic",
    encode: encoders.encodePunjabi,
    reversible: false,
    tags: ["linguistic", "punjabi", "gurmukhi"],
  },
  {
    id: "oriya-style",
    name: "Oriya Style",
    description: "Oriya script encoding",
    emoji: "🌊",
    category: "linguistic",
    encode: encoders.encodeOriya,
    reversible: false,
    tags: ["linguistic", "oriya", "south-asia"],
  },
  {
    id: "sinhala-style",
    name: "Sinhala Style",
    description: "Sri Lankan Sinhala script",
    emoji: "🇱🇰",
    category: "linguistic",
    encode: encoders.encodeSinhala,
    reversible: false,
    tags: ["linguistic", "sinhala", "sri-lanka"],
  },
  {
    id: "georgian-style",
    name: "Georgian Style",
    description: "Georgian alphabet encoding",
    emoji: "🇬🇪",
    category: "linguistic",
    encode: encoders.encodeGeorgian,
    reversible: false,
    tags: ["linguistic", "georgian", "caucasus"],
  },
  {
    id: "armenian-style",
    name: "Armenian Style",
    description: "Armenian alphabet encoding",
    emoji: "🇦🇲",
    category: "linguistic",
    encode: encoders.encodeArmenian,
    reversible: false,
    tags: ["linguistic", "armenian", "caucasus"],
  },
  {
    id: "ethiopic-style",
    name: "Ethiopic Style",
    description: "Ethiopian Ge'ez script",
    emoji: "🇪🇹",
    category: "linguistic",
    encode: encoders.encodeEthiopic,
    reversible: false,
    tags: ["linguistic", "ethiopic", "african"],
  },
  {
    id: "tibetan-style",
    name: "Tibetan Style",
    description: "Tibetan script encoding",
    emoji: "🏔️",
    category: "linguistic",
    encode: encoders.encodeTibetan,
    reversible: false,
    tags: ["linguistic", "tibetan", "central-asia"],
  },
  {
    id: "mongolian-style",
    name: "Mongolian Style",
    description: "Traditional Mongolian script",
    emoji: "🇲🇳",
    category: "linguistic",
    encode: encoders.encodeMongolian,
    reversible: false,
    tags: ["linguistic", "mongolian", "central-asia"],
  },
  {
    id: "khmer-style",
    name: "Khmer (Cambodian)",
    description: "Cambodian script encoding",
    emoji: "🇰🇭",
    category: "linguistic",
    encode: encoders.encodeKhmer,
    reversible: false,
    tags: ["linguistic", "khmer", "cambodian"],
  },
  {
    id: "myanmar-style",
    name: "Myanmar (Burmese)",
    description: "Myanmar script encoding",
    emoji: "🇲🇲",
    category: "linguistic",
    encode: encoders.encodeMyanmar,
    reversible: false,
    tags: ["linguistic", "myanmar", "burmese"],
  },
  {
    id: "lao-style",
    name: "Lao Style",
    description: "Lao script encoding",
    emoji: "🇱🇦",
    category: "linguistic",
    encode: encoders.encodeLao,
    reversible: false,
    tags: ["linguistic", "lao", "southeast-asia"],
  },
  {
    id: "javanese-style",
    name: "Javanese Style",
    description: "Javanese script encoding",
    emoji: "🏝️",
    category: "linguistic",
    encode: encoders.encodeJavanese,
    reversible: false,
    tags: ["linguistic", "javanese", "indonesian"],
  },
  {
    id: "balinese-style",
    name: "Balinese Style",
    description: "Balinese script encoding",
    emoji: "🌺",
    category: "linguistic",
    encode: encoders.encodeBalinese,
    reversible: false,
    tags: ["linguistic", "balinese", "indonesian"],
  },
  {
    id: "sundanese-style",
    name: "Sundanese Style",
    description: "Sundanese script encoding",
    emoji: "🎋",
    category: "linguistic",
    encode: encoders.encodeSundanese,
    reversible: false,
    tags: ["linguistic", "sundanese", "indonesian"],
  },
  {
    id: "cherokee-style",
    name: "Cherokee Style",
    description: "Cherokee syllabary",
    emoji: "🦅",
    category: "linguistic",
    encode: encoders.encodeCherokee,
    reversible: false,
    tags: ["linguistic", "cherokee", "native-american"],
  },
  {
    id: "canadian-aboriginal",
    name: "Canadian Aboriginal",
    description: "Canadian Aboriginal syllabics",
    emoji: "🍁",
    category: "linguistic",
    encode: encoders.encodeCanadianAboriginal,
    reversible: false,
    tags: ["linguistic", "aboriginal", "canadian"],
  },
  {
    id: "phonetic-simple",
    name: "Simple IPA",
    description: "Simple phonetic transcription",
    emoji: "🗣️",
    category: "linguistic",
    encode: encoders.encodePhoneticSimple,
    reversible: false,
    tags: ["linguistic", "phonetic", "ipa"],
  },
  {
    id: "iso-language",
    name: "ISO Language Tags",
    description: "ISO language code format",
    emoji: "🌍",
    category: "linguistic",
    encode: encoders.encodeISOLanguage,
    reversible: false,
    tags: ["linguistic", "iso", "language"],
  },
  {
    id: "phoneme-system",
    name: "Custom Phoneme System",
    description: "Fictional IPA-inspired transcription",
    emoji: "🗣️",
    category: "linguistic",
    encode: encoders.encodePhonemeSystem,
    decode: encoders.decodePhonemeSystem,
    reversible: true,
    tags: ["linguistic", "phoneme", "ipa", "transcription"],
  },
];
