import * as encoders from "../encoders/index.js";

export const militaryEncoders = [
  {
    id: "mgrs",
    name: "MGRS Coordinates",
    description: "Military Grid Reference System (NATO)",
    emoji: "🎯",
    category: "military",
    encode: encoders.encodeMGRS,
    decode: encoders.decodeMGRS,
    reversible: true,
    tags: ["military", "coordinates", "nato", "geolocation"],
  },
  {
    id: "stanag",
    name: "STANAG 4439",
    description: "NATO classification system",
    emoji: "🛡️",
    category: "military",
    encode: encoders.encodeSTANAG,
    tags: ["military", "nato", "classified", "government"],
  },
  {
    id: "prowords",
    name: "ACP 125 Prowords",
    description: "Military radio procedure words",
    emoji: "📻",
    category: "military",
    encode: encoders.encodeProwords,
    decode: encoders.decodeProwords,
    reversible: false,
    tags: ["military", "radio", "communication", "nato"],
  },
  {
    id: "classified",
    name: "US Classification Markings",
    description: "Government security classification",
    emoji: "🔒",
    category: "military",
    encode: encoders.encodeClassified,
    tags: ["military", "government", "classified", "security"],
  },
  {
    id: "zulu-time",
    name: "Zulu Time",
    description: "Military UTC time format",
    emoji: "⏰",
    category: "military",
    encode: encoders.encodeZuluTime,
    decode: encoders.decodeZuluTime,
    reversible: false,
    tags: ["military", "time", "utc", "aviation"],
  },
  {
    id: "operation-code",
    name: "Operation Code Names",
    description: "Military operation designations",
    emoji: "🎖️",
    category: "military",
    encode: encoders.encodeOperationCode,
    tags: ["military", "operations", "codenames"],
  },
  {
    id: "tactical-call-sign",
    name: "Tactical Call Signs",
    description: "Military unit identifiers",
    emoji: "📡",
    category: "military",
    encode: encoders.encodeTacticalCallSign,
    decode: encoders.decodeTacticalCallSign,
    reversible: false,
    tags: ["military", "radio", "tactical", "communications"],
  },
  {
    id: "brevity-code",
    name: "NATO Brevity Codes",
    description: "Air combat communication codes",
    emoji: "✈️",
    category: "military",
    encode: encoders.encodeBrevityCode,
    decode: encoders.decodeBrevityCode,
    reversible: false,
    tags: ["military", "aviation", "nato", "tactical"],
  },
  {
    id: "georef",
    name: "GEOREF",
    description: "World Geographic Reference System",
    emoji: "🌍",
    category: "military",
    encode: encoders.encodeGEOREF,
    decode: encoders.decodeGEOREF,
    reversible: false,
    tags: ["military", "coordinates", "aviation", "navigation"],
  },
  {
    id: "sigint",
    name: "SIGINT Format",
    description: "Signals intelligence identifiers",
    emoji: "📡",
    category: "military",
    encode: encoders.encodeSIGINT,
    tags: ["military", "intelligence", "classified", "security"],
  },
  {
    id: "weapon-designation",
    name: "Weapon Designation",
    description: "US military weapon system codes",
    emoji: "🚀",
    category: "military",
    encode: encoders.encodeWeaponDesignation,
    tags: ["military", "weapons", "designation", "systems"],
  },
];
