import * as encoders from "../encoders/index.js";

export const modernEncoders = [
  {
    id: "code128",
    name: "Code128 Barcode",
    description: "Barcode pattern encoding",
    emoji: "▐",
    category: "modern",
    encode: encoders.encodeCode128,
    reversible: false,
    tags: ["modern", "barcode", "visual"],
  },
  {
    id: "datamatrix",
    name: "DataMatrix",
    description: "2D barcode pattern",
    emoji: "⬛",
    category: "modern",
    encode: encoders.encodeDataMatrix,
    reversible: false,
    tags: ["modern", "datamatrix", "2d-barcode"],
  },
  {
    id: "pdf417",
    name: "PDF417 Pattern",
    description: "PDF417 barcode style",
    emoji: "📊",
    category: "modern",
    encode: encoders.encodePDF417,
    reversible: false,
    tags: ["modern", "pdf417", "barcode"],
  },
  {
    id: "hashtag",
    name: "Hashtag Encoding",
    description: "Social media hashtags",
    emoji: "#️⃣",
    category: "modern",
    encode: encoders.encodeHashtag,
    reversible: false,
    tags: ["modern", "hashtag", "social"],
  },
  {
    id: "emoji-reaction",
    name: "Emoji Reactions",
    description: "Social media reactions",
    emoji: "👍",
    category: "modern",
    encode: encoders.encodeEmojiReaction,
    reversible: false,
    tags: ["modern", "emoji", "reactions"],
  },
  {
    id: "mention",
    name: "@Mention Format",
    description: "Social media mentions",
    emoji: "@",
    category: "modern",
    encode: encoders.encodeMention,
    reversible: false,
    tags: ["modern", "mention", "social"],
  },
  {
    id: "short-url",
    name: "Short URL Style",
    description: "URL shortener format",
    emoji: "🔗",
    category: "modern",
    encode: encoders.encodeShortURL,
    reversible: false,
    tags: ["modern", "url", "shortener"],
  },
  {
    id: "git-commit",
    name: "Git Commit Hash",
    description: "Git-style commit IDs",
    emoji: "📝",
    category: "modern",
    encode: encoders.encodeGitCommit,
    decode: encoders.decodeGitCommit,
    reversible: true,
    tags: ["modern", "git", "commit"],
  },
  {
    id: "json-path",
    name: "JSON Path",
    description: "JSON path notation",
    emoji: "{}",
    category: "modern",
    encode: encoders.encodeJSONPath,
    reversible: false,
    tags: ["modern", "json", "path"],
  },
  {
    id: "css-color",
    name: "CSS Color",
    description: "Hex color codes",
    emoji: "🎨",
    category: "modern",
    encode: encoders.encodeCSSColor,
    decode: encoders.decodeCSSColor,
    reversible: true,
    tags: ["modern", "css", "color"],
  },
  {
    id: "pixel-coord",
    name: "Pixel Coordinates",
    description: "Screen pixel positions",
    emoji: "📺",
    category: "modern",
    encode: encoders.encodePixelCoord,
    reversible: false,
    tags: ["modern", "pixel", "coordinates"],
  },
  {
    id: "api-endpoint",
    name: "API Endpoint",
    description: "REST API format",
    emoji: "🔌",
    category: "modern",
    encode: encoders.encodeAPIEndpoint,
    reversible: false,
    tags: ["modern", "api", "rest"],
  },
  {
    id: "cron",
    name: "Cron Expression",
    description: "Cron schedule format",
    emoji: "⏰",
    category: "modern",
    encode: encoders.encodeCron,
    reversible: false,
    tags: ["modern", "cron", "schedule"],
  },
  {
    id: "version",
    name: "SemVer Version",
    description: "Semantic versioning",
    emoji: "v",
    category: "modern",
    encode: encoders.encodeVersion,
    decode: encoders.decodeVersion,
    reversible: true,
    tags: ["modern", "version", "semver"],
  },
  {
    id: "log-level",
    name: "Log Level Format",
    description: "Application log style",
    emoji: "📋",
    category: "modern",
    encode: encoders.encodeLogLevel,
    reversible: false,
    tags: ["modern", "log", "debug"],
  },
  {
    id: "env-var",
    name: "Environment Variables",
    description: "ENV var format",
    emoji: "🔧",
    category: "modern",
    encode: encoders.encodeEnvVar,
    reversible: false,
    tags: ["modern", "env", "config"],
  },
  {
    id: "docker-tag",
    name: "Docker Tags",
    description: "Container image tags",
    emoji: "🐳",
    category: "modern",
    encode: encoders.encodeDockerTag,
    reversible: false,
    tags: ["modern", "docker", "container"],
  },
  {
    id: "k8s-label",
    name: "Kubernetes Labels",
    description: "K8s label format",
    emoji: "☸️",
    category: "modern",
    encode: encoders.encodeK8sLabel,
    reversible: false,
    tags: ["modern", "kubernetes", "labels"],
  },
  {
    id: "wifi-signal",
    name: "WiFi Signal",
    description: "Signal strength pattern",
    emoji: "📶",
    category: "modern",
    encode: encoders.encodeWiFiSignal,
    reversible: false,
    tags: ["modern", "wifi", "signal"],
  },
  {
    id: "battery",
    name: "Battery Level",
    description: "Battery indicator",
    emoji: "🔋",
    category: "modern",
    encode: encoders.encodeBattery,
    reversible: false,
    tags: ["modern", "battery", "indicator"],
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    description: "Loading bar pattern",
    emoji: "▓",
    category: "modern",
    encode: encoders.encodeProgressBar,
    reversible: false,
    tags: ["modern", "progress", "loading"],
  },
  {
    id: "notification-badge",
    name: "Notification Badge",
    description: "App notification style",
    emoji: "🔔",
    category: "modern",
    encode: encoders.encodeNotificationBadge,
    reversible: false,
    tags: ["modern", "notification", "badge"],
  },
  {
    id: "status-indicator",
    name: "Status Indicator",
    description: "Online/offline status",
    emoji: "🟢",
    category: "modern",
    encode: encoders.encodeStatus,
    reversible: false,
    tags: ["modern", "status", "online"],
  },
  {
    id: "file-size",
    name: "File Size",
    description: "Byte size format",
    emoji: "📁",
    category: "modern",
    encode: encoders.encodeFileSize,
    reversible: false,
    tags: ["modern", "file", "size"],
  },
  {
    id: "rating",
    name: "Star Rating",
    description: "5-star rating format",
    emoji: "⭐",
    category: "modern",
    encode: encoders.encodeRating,
    reversible: false,
    tags: ["modern", "rating", "stars"],
  },
  {
    id: "checkbox",
    name: "Checkbox Todo",
    description: "Task checkbox format",
    emoji: "☑️",
    category: "modern",
    encode: encoders.encodeCheckbox,
    reversible: false,
    tags: ["modern", "checkbox", "todo"],
  },
  {
    id: "stock-ticker",
    name: "Stock Ticker",
    description: "Stock market ticker format",
    emoji: "📈",
    category: "modern",
    encode: encoders.encodeStockTicker,
    reversible: false,
    tags: ["modern", "stock", "finance"],
  },
  {
    id: "swift-code",
    name: "SWIFT Code",
    description: "Bank SWIFT code format",
    emoji: "🏦",
    category: "modern",
    encode: encoders.encodeSWIFT,
    reversible: false,
    tags: ["modern", "bank", "swift"],
  },
  {
    id: "relative-time",
    name: "Relative Time",
    description: "Human-readable time ago",
    emoji: "🕐",
    category: "modern",
    encode: encoders.encodeRelativeTime,
    reversible: false,
    tags: ["modern", "time", "relative"],
  },
  {
    id: "what3words-style",
    name: "What3Words Style",
    description: "Three-word location format",
    emoji: "📍",
    category: "modern",
    encode: encoders.encodeWhat3Words,
    reversible: false,
    tags: ["modern", "location", "words"],
  },
  {
    id: "vcard-format",
    name: "vCard Format",
    description: "Contact card format",
    emoji: "📇",
    category: "modern",
    encode: encoders.encodeVCard,
    reversible: false,
    tags: ["modern", "vcard", "contact"],
  },
  {
    id: "wifi-qr",
    name: "WiFi QR Format",
    description: "WiFi network QR format",
    emoji: "📶",
    category: "modern",
    encode: encoders.encodeWiFiQR,
    reversible: false,
    tags: ["modern", "wifi", "qr"],
  },
  {
    id: "ical-event",
    name: "iCal Event",
    description: "Calendar event format",
    emoji: "🗓️",
    category: "modern",
    encode: encoders.encodeICal,
    reversible: false,
    tags: ["modern", "ical", "calendar"],
  },
  {
    id: "twitter-style",
    name: "Twitter Style",
    description: "Twitter post with hashtags",
    emoji: "🐦",
    category: "modern",
    encode: encoders.encodeTwitterStyle,
    reversible: false,
    tags: ["modern", "twitter", "social"],
  },
  {
    id: "reddit-style",
    name: "Reddit Style",
    description: "Reddit post format",
    emoji: "🤖",
    category: "modern",
    encode: encoders.encodeRedditStyle,
    reversible: false,
    tags: ["modern", "reddit", "social"],
  },
  {
    id: "forum-quote",
    name: "Forum Quote",
    description: "BBCode forum quote",
    emoji: "💬",
    category: "modern",
    encode: encoders.encodeForumQuote,
    reversible: false,
    tags: ["modern", "forum", "bbcode"],
  },
];
