import * as encoders from "../encoders/index.js";

export const natureEncoders = [
  {
    id: "rna",
    name: "RNA Sequence",
    description: "AUGC base encoding",
    emoji: "🧬",
    category: "nature",
    encode: encoders.encodeRNA,
    decode: encoders.decodeRNA,
    reversible: true,
    tags: ["nature", "rna", "biology"],
  },
  {
    id: "amino-acid",
    name: "Amino Acid Sequence",
    description: "Protein sequence encoding",
    emoji: "🥩",
    category: "nature",
    encode: encoders.encodeAminoAcid,
    reversible: false,
    tags: ["nature", "protein", "biology"],
  },
  {
    id: "codon",
    name: "Codon Triplets",
    description: "Genetic codon encoding",
    emoji: "🧪",
    category: "nature",
    encode: encoders.encodeCodon,
    reversible: false,
    tags: ["nature", "codon", "genetics"],
  },
  {
    id: "plant-taxonomy",
    name: "Plant Taxonomy",
    description: "Botanical species names",
    emoji: "🌱",
    category: "nature",
    encode: encoders.encodePlantTaxonomy,
    reversible: false,
    tags: ["nature", "plant", "taxonomy"],
  },
  {
    id: "animal-taxonomy",
    name: "Animal Taxonomy",
    description: "Zoological species names",
    emoji: "🦁",
    category: "nature",
    encode: encoders.encodeAnimalTaxonomy,
    reversible: false,
    tags: ["nature", "animal", "taxonomy"],
  },
  {
    id: "constellation",
    name: "Constellation",
    description: "Star constellation encoding",
    emoji: "⭐",
    category: "nature",
    encode: encoders.encodeConstellation,
    reversible: false,
    tags: ["nature", "constellation", "astronomy"],
  },
  {
    id: "mineral",
    name: "Mineral Encoding",
    description: "Geological mineral names",
    emoji: "💎",
    category: "nature",
    encode: encoders.encodeMineral,
    reversible: false,
    tags: ["nature", "mineral", "geology"],
  },
  {
    id: "geological-era",
    name: "Geological Era",
    description: "Earth history periods",
    emoji: "🌍",
    category: "nature",
    encode: encoders.encodeGeologicalEra,
    reversible: false,
    tags: ["nature", "geology", "era"],
  },
  {
    id: "flower",
    name: "Flower Encoding",
    description: "Botanical flower names",
    emoji: "🌸",
    category: "nature",
    encode: encoders.encodeFlower,
    reversible: false,
    tags: ["nature", "flower", "botanical"],
  },
  {
    id: "butterfly-wing",
    name: "Butterfly Wing",
    description: "Wing pattern encoding",
    emoji: "🦋",
    category: "nature",
    encode: encoders.encodeButterflyWing,
    reversible: false,
    tags: ["nature", "butterfly", "pattern"],
  },
  {
    id: "seashell",
    name: "Seashell Pattern",
    description: "Shell type encoding",
    emoji: "🐚",
    category: "nature",
    encode: encoders.encodeSeashell,
    reversible: false,
    tags: ["nature", "seashell", "marine"],
  },
  {
    id: "cloud-type",
    name: "Cloud Type",
    description: "Meteorological clouds",
    emoji: "☁️",
    category: "nature",
    encode: encoders.encodeCloudType,
    reversible: false,
    tags: ["nature", "cloud", "weather"],
  },
  {
    id: "terrain",
    name: "Terrain Features",
    description: "Geographic features",
    emoji: "🏔️",
    category: "nature",
    encode: encoders.encodeTerrain,
    reversible: false,
    tags: ["nature", "terrain", "geography"],
  },
  {
    id: "ecosystem",
    name: "Ecosystem",
    description: "Biome encoding",
    emoji: "🌲",
    category: "nature",
    encode: encoders.encodeEcosystem,
    reversible: false,
    tags: ["nature", "ecosystem", "biome"],
  },
  {
    id: "bird-call",
    name: "Bird Call",
    description: "Avian vocalization",
    emoji: "🐦",
    category: "nature",
    encode: encoders.encodeBirdCall,
    reversible: false,
    tags: ["nature", "bird", "sound"],
  },
  {
    id: "paw-print",
    name: "Paw Print",
    description: "Animal track pattern",
    emoji: "🐾",
    category: "nature",
    encode: encoders.encodePawPrint,
    reversible: false,
    tags: ["nature", "paw", "animal"],
  },
  {
    id: "leaf-pattern",
    name: "Leaf Pattern",
    description: "Botanical leaf encoding",
    emoji: "🍃",
    category: "nature",
    encode: encoders.encodeLeafPattern,
    reversible: false,
    tags: ["nature", "leaf", "botanical"],
  },
  {
    id: "crystal-structure",
    name: "Crystal Structure",
    description: "Crystallographic encoding",
    emoji: "💎",
    category: "nature",
    encode: encoders.encodeCrystalStructure,
    reversible: false,
    tags: ["nature", "crystal", "mineralogy"],
  },
  {
    id: "ocean-depth",
    name: "Ocean Depth Zones",
    description: "Pelagic zone encoding",
    emoji: "🌊",
    category: "nature",
    encode: encoders.encodeOceanDepth,
    reversible: false,
    tags: ["nature", "ocean", "marine"],
  },
  {
    id: "insect",
    name: "Insect Encoding",
    description: "Entomological encoding",
    emoji: "🐜",
    category: "nature",
    encode: encoders.encodeInsect,
    reversible: false,
    tags: ["nature", "insect", "entomology"],
  },
  {
    id: "volcano",
    name: "Volcano Activity",
    description: "Volcanic activity encoding",
    emoji: "🌋",
    category: "nature",
    encode: encoders.encodeVolcano,
    reversible: false,
    tags: ["nature", "volcano", "geology"],
  },
  {
    id: "cell-organelle",
    name: "Cell Organelle",
    description: "Cellular structure encoding",
    emoji: "🔬",
    category: "nature",
    encode: encoders.encodeCellOrganelle,
    reversible: false,
    tags: ["nature", "cell", "biology"],
  },
  {
    id: "origami-crease",
    name: "Origami Crease Pattern",
    description: "Mountain/valley fold patterns",
    emoji: "📄",
    category: "nature",
    encode: encoders.encodeOrigamiCrease,
    decode: encoders.decodeOrigamiCrease,
    reversible: true,
    tags: ["nature", "origami", "patterns", "art"],
  },
  {
    id: "constellation-map",
    name: "Constellation Map",
    description: "Star positions and magnitudes",
    emoji: "⭐",
    category: "nature",
    encode: encoders.encodeConstellationMap,
    decode: encoders.decodeConstellationMap,
    reversible: true,
    tags: ["nature", "astronomy", "stars", "celestial"],
  },
  {
    id: "tectonic-plate",
    name: "Tectonic Plate Movement",
    description: "Plate boundary dynamics",
    emoji: "🌍",
    category: "nature",
    encode: encoders.encodeTectonicPlate,
    decode: encoders.decodeTectonicPlate,
    reversible: true,
    tags: ["nature", "geology", "tectonics", "earth"],
  },
  {
    id: "mycelium-network",
    name: "Mycelium Network",
    description: "Fungal connection patterns",
    emoji: "🍄",
    category: "nature",
    encode: encoders.encodeMyceliumNetwork,
    decode: encoders.decodeMyceliumNetwork,
    reversible: true,
    tags: ["nature", "biology", "fungi", "network"],
  },
  {
    id: "bioluminescence",
    name: "Bioluminescence",
    description: "Light wavelength patterns",
    emoji: "💫",
    category: "nature",
    encode: encoders.encodeBioluminescence,
    decode: encoders.decodeBioluminescence,
    reversible: true,
    tags: ["nature", "biology", "light", "ocean"],
  },
  {
    id: "aurora-borealis",
    name: "Aurora Borealis",
    description: "Northern lights patterns",
    emoji: "🌌",
    category: "nature",
    encode: encoders.encodeAuroraBorealis,
    decode: encoders.decodeAuroraBorealis,
    reversible: true,
    tags: ["nature", "aurora", "atmospheric", "polar"],
  },
  {
    id: "waggle-dance",
    name: "Bee Waggle Dance",
    description: "Honeybee communication",
    emoji: "🐝",
    category: "nature",
    encode: encoders.encodeWaggleDance,
    decode: encoders.decodeWaggleDance,
    reversible: true,
    tags: ["nature", "biology", "bees", "communication"],
  },
  {
    id: "glacier-stratigraphy",
    name: "Glacier Stratigraphy",
    description: "Ice core layer patterns",
    emoji: "🧊",
    category: "nature",
    encode: encoders.encodeGlacierStratigraphy,
    decode: encoders.decodeGlacierStratigraphy,
    reversible: true,
    tags: ["nature", "geology", "ice", "climate"],
  },
  {
    id: "wind-rose",
    name: "Wind Rose Pattern",
    description: "Wind direction patterns",
    emoji: "🌬️",
    category: "nature",
    encode: encoders.encodeWindRose,
    decode: encoders.decodeWindRose,
    reversible: true,
    tags: ["nature", "weather", "wind", "meteorology"],
  },
  {
    id: "dendrochronology",
    name: "Dendrochronology",
    description: "Tree ring patterns",
    emoji: "🌳",
    category: "nature",
    encode: encoders.encodeDendrochronology,
    decode: encoders.decodeDendrochronology,
    reversible: true,
    tags: ["nature", "trees", "dating", "ecology"],
  },
  {
    id: "coral-reef",
    name: "Coral Reef Pattern",
    description: "Coral polyp patterns",
    emoji: "🪸",
    category: "nature",
    encode: encoders.encodeCoralReef,
    decode: encoders.decodeCoralReef,
    reversible: true,
    tags: ["nature", "marine", "coral", "ecosystem"],
  },
  {
    id: "bird-migration",
    name: "Bird Migration",
    description: "Migration flight patterns",
    emoji: "🦅",
    category: "nature",
    encode: encoders.encodeBirdMigration,
    decode: encoders.decodeBirdMigration,
    reversible: true,
    tags: ["nature", "birds", "migration", "ecology"],
  },
  {
    id: "erosion-pattern",
    name: "Erosion Pattern",
    description: "Geological erosion types",
    emoji: "🏜️",
    category: "nature",
    encode: encoders.encodeErosionPattern,
    decode: encoders.decodeErosionPattern,
    reversible: true,
    tags: ["nature", "geology", "erosion", "landscape"],
  },
  {
    id: "aurora-australis",
    name: "Aurora Australis",
    description: "Southern lights patterns",
    emoji: "✨",
    category: "nature",
    encode: encoders.encodeAuroraAustralis,
    decode: encoders.decodeAuroraAustralis,
    reversible: true,
    tags: ["nature", "aurora", "atmospheric", "southern"],
  },
  {
    id: "snowflake-crystal",
    name: "Snowflake Crystal",
    description: "Ice crystal structures",
    emoji: "❄️",
    category: "nature",
    encode: encoders.encodeSnowflakeCrystal,
    decode: encoders.decodeSnowflakeCrystal,
    reversible: true,
    tags: ["nature", "crystal", "snow", "winter"],
  },
  {
    id: "bonsai-growth",
    name: "Bonsai Growth",
    description: "Bonsai styling patterns",
    emoji: "🌲",
    category: "nature",
    encode: encoders.encodeBonsaiGrowth,
    decode: encoders.decodeBonsaiGrowth,
    reversible: true,
    tags: ["nature", "bonsai", "art", "cultivation"],
  },
];
