import * as encoders from "../encoders/index.js";

export const patternsEncoders = [
  {
    id: "fibonacci",
    name: "Fibonacci Encoding",
    description: "Maps characters to Fibonacci sequence",
    emoji: "🌀",
    category: "patterns",
    encode: encoders.encodeFibonacci,
    decode: encoders.decodeFibonacci,
    reversible: false,
    tags: ["patterns", "mathematical", "fibonacci"],
  },
  {
    id: "prime",
    name: "Prime Number Encoding",
    description: "Uses prime numbers for positions",
    emoji: "🔢",
    category: "patterns",
    encode: encoders.encodePrime,
    decode: encoders.decodePrime,
    reversible: true,
    tags: ["patterns", "mathematical", "prime"],
  },
  {
    id: "golden-ratio",
    name: "Golden Ratio Encoding",
    description: "Phi-based mathematical encoding",
    emoji: "φ",
    category: "patterns",
    encode: encoders.encodeGoldenRatio,
    decode: encoders.decodeGoldenRatio,
    reversible: false,
    tags: ["patterns", "mathematical", "golden"],
  },
  {
    id: "triangle",
    name: "Triangle Number Encoding",
    description: "Uses triangular number sequence",
    emoji: "△",
    category: "patterns",
    encode: encoders.encodeTriangle,
    reversible: false,
    tags: ["patterns", "mathematical", "sequence"],
  },
  {
    id: "square-number",
    name: "Square Number Encoding",
    description: "Perfect square encoding",
    emoji: "□",
    category: "patterns",
    encode: encoders.encodeSquareNumber,
    reversible: false,
    tags: ["patterns", "mathematical", "square"],
  },
  {
    id: "hexagram-pattern",
    name: "Hexagram Pattern",
    description: "I-Ching style patterns",
    emoji: "☯",
    category: "patterns",
    encode: encoders.encodeHexagramPattern,
    reversible: false,
    tags: ["patterns", "iching", "mystical"],
  },
  {
    id: "binary-tree",
    name: "Binary Tree Path",
    description: "Left/right tree traversal",
    emoji: "🌳",
    category: "patterns",
    encode: encoders.encodeBinaryTree,
    decode: encoders.decodeBinaryTree,
    reversible: true,
    tags: ["patterns", "tree", "path"],
  },
  {
    id: "matrix-coord",
    name: "Matrix Coordinates",
    description: "Row/column coordinate encoding",
    emoji: "📐",
    category: "patterns",
    encode: encoders.encodeMatrixCoord,
    decode: encoders.decodeMatrixCoord,
    reversible: true,
    tags: ["patterns", "matrix", "coordinates"],
  },
  {
    id: "spiral",
    name: "Spiral Pattern",
    description: "Spiral rotation encoding",
    emoji: "🌀",
    category: "patterns",
    encode: encoders.encodeSpiral,
    reversible: false,
    tags: ["patterns", "spiral", "geometric"],
  },
  {
    id: "wave-pattern",
    name: "Wave Pattern",
    description: "Sinusoidal wave encoding",
    emoji: "〰️",
    category: "patterns",
    encode: encoders.encodeWavePattern,
    reversible: false,
    tags: ["patterns", "wave", "sinusoidal"],
  },
  {
    id: "fractal",
    name: "Fractal Pattern",
    description: "Self-similar fractal encoding",
    emoji: "❄️",
    category: "patterns",
    encode: encoders.encodeFractal,
    reversible: false,
    tags: ["patterns", "fractal", "geometric"],
  },
  {
    id: "pascal",
    name: "Pascal Triangle",
    description: "Pascal's triangle encoding",
    emoji: "▲",
    category: "patterns",
    encode: encoders.encodePascal,
    reversible: false,
    tags: ["patterns", "pascal", "mathematical"],
  },
  {
    id: "rule30",
    name: "Rule 30 Automaton",
    description: "Cellular automaton encoding",
    emoji: "🤖",
    category: "patterns",
    encode: encoders.encodeRule30,
    reversible: false,
    tags: ["patterns", "automaton", "cellular"],
  },
  {
    id: "checksum",
    name: "Checksum Encoding",
    description: "Hex with checksum verification",
    emoji: "✓",
    category: "patterns",
    encode: encoders.encodeChecksum,
    reversible: false,
    tags: ["patterns", "checksum", "verification"],
  },
  {
    id: "crc",
    name: "CRC Pattern",
    description: "CRC-like error checking",
    emoji: "∑",
    category: "patterns",
    encode: encoders.encodeCRC,
    reversible: false,
    tags: ["patterns", "crc", "error-checking"],
  },
  {
    id: "hamming",
    name: "Hamming Code (7,4)",
    description: "Error-correcting Hamming code",
    emoji: "H",
    category: "patterns",
    encode: encoders.encodeHamming,
    reversible: false,
    tags: ["patterns", "hamming", "error-correction"],
  },
  {
    id: "gray-code",
    name: "Gray Code",
    description: "Single-bit change encoding",
    emoji: "◐",
    category: "patterns",
    encode: encoders.encodeGrayCode,
    decode: encoders.decodeGrayCode,
    reversible: true,
    tags: ["patterns", "gray", "binary"],
  },
  {
    id: "manchester",
    name: "Manchester Encoding",
    description: "Clock + data signal encoding",
    emoji: "↕️",
    category: "patterns",
    encode: encoders.encodeManchester,
    decode: encoders.decodeManchester,
    reversible: true,
    tags: ["patterns", "manchester", "signal"],
  },
];
