import * as encoders from "../encoders/index.js";

export const retroEncoders = [
  {
    id: "phone-keypad",
    name: "Phone Keypad (T9)",
    description: "Old mobile phone multi-tap",
    emoji: "📱",
    category: "retro",
    encode: encoders.encodePhoneKeypad,
    decode: encoders.decodePhoneKeypad,
    reversible: true,
    tags: ["retro", "phone", "t9"],
  },
  {
    id: "pager",
    name: "Pager Code",
    description: "Classic pager numeric codes",
    emoji: "📟",
    category: "retro",
    encode: encoders.encodePagerCode,
    reversible: false,
    tags: ["retro", "pager", "numeric"],
  },
  {
    id: "punch-card",
    name: "IBM Punch Card",
    description: "Vintage punch card patterns",
    emoji: "🎫",
    category: "retro",
    encode: encoders.encodePunchCard,
    reversible: false,
    tags: ["retro", "punchcard", "ibm"],
  },
  {
    id: "baudot",
    name: "Baudot Code",
    description: "5-bit teleprinter code",
    emoji: "📟",
    category: "retro",
    encode: encoders.encodeBaudot,
    decode: encoders.decodeBaudot,
    reversible: true,
    tags: ["retro", "teleprinter", "telegraph"],
  },
  {
    id: "resistor",
    name: "Resistor Color Code",
    description: "Electronics color bands",
    emoji: "⚡",
    category: "retro",
    encode: encoders.encodeResistor,
    reversible: false,
    tags: ["retro", "electronics", "engineering"],
  },
  {
    id: "cb-radio",
    name: "CB Radio Style",
    description: "10-codes CB radio format",
    emoji: "📻",
    category: "retro",
    encode: encoders.encodeCBRadio,
    reversible: false,
    tags: ["retro", "radio", "cb"],
  },
  {
    id: "radio-operator",
    name: "Radio Operator",
    description: "Ham radio operator style",
    emoji: "📡",
    category: "retro",
    encode: encoders.encodeRadioOperator,
    reversible: false,
    tags: ["retro", "radio", "ham"],
  },
  {
    id: "teletype",
    name: "Teletype Message",
    description: "Classic teletype format",
    emoji: "📟",
    category: "retro",
    encode: encoders.encodeTeletype,
    reversible: false,
    tags: ["retro", "teletype", "telex"],
  },
  {
    id: "wire-service",
    name: "Wire Service",
    description: "News wire service format",
    emoji: "📰",
    category: "retro",
    encode: encoders.encodeWireService,
    reversible: false,
    tags: ["retro", "news", "wire"],
  },
];
