import * as encoders from "../encoders/index.js";

export const scientificEncoders = [
  {
    id: "scientific-notation",
    name: "Scientific Notation",
    description: "Mantissa × 10^exponent",
    emoji: "🔬",
    category: "scientific",
    encode: encoders.encodeScientific,
    decode: encoders.decodeScientific,
    reversible: true,
    tags: ["scientific", "notation", "math"],
  },
  {
    id: "physics-constants",
    name: "Physics Constants",
    description: "Physical constant encoding",
    emoji: "⚛️",
    category: "scientific",
    encode: encoders.encodePhysicsConstants,
    reversible: false,
    tags: ["scientific", "physics", "constants"],
  },
  {
    id: "chemical-formula",
    name: "Chemical Formula",
    description: "Chemical compound notation",
    emoji: "⚗️",
    category: "scientific",
    encode: encoders.encodeChemicalFormula,
    reversible: false,
    tags: ["scientific", "chemistry", "formula"],
  },
  {
    id: "molecular",
    name: "Molecular Structure",
    description: "Molecular bond notation",
    emoji: "🧪",
    category: "scientific",
    encode: encoders.encodeMolecular,
    reversible: false,
    tags: ["scientific", "molecular", "bonds"],
  },
  {
    id: "electron-config",
    name: "Electron Configuration",
    description: "Atomic orbital notation",
    emoji: "⚡",
    category: "scientific",
    encode: encoders.encodeElectronConfig,
    reversible: false,
    tags: ["scientific", "electron", "orbital"],
  },
  {
    id: "quantum-state",
    name: "Quantum State",
    description: "Qubit state notation",
    emoji: "🔮",
    category: "scientific",
    encode: encoders.encodeQuantumState,
    reversible: false,
    tags: ["scientific", "quantum", "physics"],
  },
  {
    id: "calculus",
    name: "Calculus Notation",
    description: "Mathematical operators",
    emoji: "∫",
    category: "scientific",
    encode: encoders.encodeCalculus,
    reversible: false,
    tags: ["scientific", "calculus", "math"],
  },
  {
    id: "matrix-notation",
    name: "Matrix Notation",
    description: "2x2 matrix format",
    emoji: "⎡⎤",
    category: "scientific",
    encode: encoders.encodeMatrix,
    reversible: false,
    tags: ["scientific", "matrix", "linear-algebra"],
  },
  {
    id: "vector-notation",
    name: "Vector Notation",
    description: "3D vector format",
    emoji: "→",
    category: "scientific",
    encode: encoders.encodeVector,
    decode: encoders.decodeVector,
    reversible: true,
    tags: ["scientific", "vector", "math"],
  },
  {
    id: "complex-number",
    name: "Complex Numbers",
    description: "Real + imaginary format",
    emoji: "i",
    category: "scientific",
    encode: encoders.encodeComplex,
    decode: encoders.decodeComplex,
    reversible: true,
    tags: ["scientific", "complex", "imaginary"],
  },
  {
    id: "polar-coord",
    name: "Polar Coordinates",
    description: "Radius + angle format",
    emoji: "🎯",
    category: "scientific",
    encode: encoders.encodePolar,
    reversible: false,
    tags: ["scientific", "polar", "coordinates"],
  },
  {
    id: "periodic-table",
    name: "Periodic Table Names",
    description: "Full element names",
    emoji: "⚛️",
    category: "scientific",
    encode: encoders.encodePeriodicTable,
    reversible: false,
    tags: ["scientific", "periodic", "elements"],
  },
  {
    id: "si-units",
    name: "SI Units",
    description: "Metric unit encoding",
    emoji: "📏",
    category: "scientific",
    encode: encoders.encodeSIUnits,
    reversible: false,
    tags: ["scientific", "units", "metric"],
  },
  {
    id: "astronomical",
    name: "Astronomical Coords",
    description: "RA/DEC coordinates",
    emoji: "🌌",
    category: "scientific",
    encode: encoders.encodeAstronomical,
    reversible: false,
    tags: ["scientific", "astronomy", "coordinates"],
  },
  {
    id: "wave-function",
    name: "Wave Function",
    description: "Amplitude/frequency notation",
    emoji: "〜",
    category: "scientific",
    encode: encoders.encodeWaveFunction,
    reversible: false,
    tags: ["scientific", "wave", "physics"],
  },
  {
    id: "statistics",
    name: "Statistical Notation",
    description: "Statistical symbols",
    emoji: "σ",
    category: "scientific",
    encode: encoders.encodeStatistics,
    reversible: false,
    tags: ["scientific", "statistics", "math"],
  },
  {
    id: "thermodynamic",
    name: "Thermodynamic",
    description: "Thermodynamic variables",
    emoji: "🌡️",
    category: "scientific",
    encode: encoders.encodeThermodynamic,
    reversible: false,
    tags: ["scientific", "thermodynamics", "physics"],
  },
  {
    id: "logic-gates",
    name: "Logic Gates",
    description: "Boolean logic encoding",
    emoji: "🔲",
    category: "scientific",
    encode: encoders.encodeLogicGates,
    reversible: false,
    tags: ["scientific", "logic", "boolean"],
  },
  {
    id: "tensor",
    name: "Tensor Notation",
    description: "Tensor index notation",
    emoji: "⊗",
    category: "scientific",
    encode: encoders.encodeTensor,
    reversible: false,
    tags: ["scientific", "tensor", "math"],
  },
  {
    id: "set-theory",
    name: "Set Theory",
    description: "Set notation encoding",
    emoji: "∈",
    category: "scientific",
    encode: encoders.encodeSetTheory,
    reversible: false,
    tags: ["scientific", "set", "math"],
  },
  {
    id: "geometry-notation",
    name: "Geometry Notation",
    description: "Geometric symbols",
    emoji: "📐",
    category: "scientific",
    encode: encoders.encodeGeometry,
    reversible: false,
    tags: ["scientific", "geometry", "shapes"],
  },
  {
    id: "number-theory",
    name: "Number Theory",
    description: "Divisor notation",
    emoji: "÷",
    category: "scientific",
    encode: encoders.encodeNumberTheory,
    reversible: false,
    tags: ["scientific", "number-theory", "divisors"],
  },
  {
    id: "utm-coords",
    name: "UTM Coordinates",
    description: "Universal Transverse Mercator",
    emoji: "🗺️",
    category: "scientific",
    encode: encoders.encodeUTM,
    reversible: false,
    tags: ["scientific", "utm", "coordinates"],
  },
  {
    id: "fluid-dynamics",
    name: "Fluid Dynamics",
    description: "Flow regime patterns",
    emoji: "🌊",
    category: "scientific",
    encode: encoders.encodeFluidDynamics,
    decode: encoders.decodeFluidDynamics,
    reversible: true,
    tags: ["scientific", "physics", "fluids", "dynamics"],
  },
  {
    id: "crystallography-lattice",
    name: "Crystallography Lattice",
    description: "Crystal lattice structures",
    emoji: "💎",
    category: "scientific",
    encode: encoders.encodeCrystallography,
    decode: encoders.decodeCrystallography,
    reversible: true,
    tags: ["scientific", "crystal", "lattice", "chemistry"],
  },
  {
    id: "seismograph",
    name: "Seismograph Wave",
    description: "Seismic wave patterns",
    emoji: "📉",
    category: "scientific",
    encode: encoders.encodeSeismograph,
    decode: encoders.decodeSeismograph,
    reversible: true,
    tags: ["scientific", "geology", "earthquake", "waves"],
  },
  {
    id: "magnetic-field",
    name: "Magnetic Field Lines",
    description: "Magnetic field patterns",
    emoji: "🧲",
    category: "scientific",
    encode: encoders.encodeMagneticField,
    decode: encoders.decodeMagneticField,
    reversible: true,
    tags: ["scientific", "physics", "magnetic", "electromagnetism"],
  },
  {
    id: "supernova-remnant",
    name: "Supernova Remnant",
    description: "Stellar explosion patterns",
    emoji: "💥",
    category: "scientific",
    encode: encoders.encodeSupernovaRemnant,
    decode: encoders.decodeSupernovaRemnant,
    reversible: true,
    tags: ["scientific", "astronomy", "supernova", "stellar"],
  },
  {
    id: "circadian-rhythm",
    name: "Circadian Rhythm",
    description: "Biological clock patterns",
    emoji: "🌅",
    category: "scientific",
    encode: encoders.encodeCircadianRhythm,
    decode: encoders.decodeCircadianRhythm,
    reversible: true,
    tags: ["scientific", "biology", "circadian", "hormones"],
  },
  {
    id: "holographic-interference",
    name: "Holographic Interference",
    description: "Laser interference patterns",
    emoji: "🌈",
    category: "scientific",
    encode: encoders.encodeHolographicInterference,
    decode: encoders.decodeHolographicInterference,
    reversible: true,
    tags: ["scientific", "physics", "holography", "optics"],
  },
  {
    id: "fermentation",
    name: "Fermentation Process",
    description: "Microbial fermentation",
    emoji: "🧫",
    category: "scientific",
    encode: encoders.encodeFermentation,
    decode: encoders.decodeFermentation,
    reversible: true,
    tags: ["scientific", "biology", "fermentation", "microbiology"],
  },
  {
    id: "neurotransmitter",
    name: "Neurotransmitter Pattern",
    description: "Neural signaling patterns",
    emoji: "🧠",
    category: "scientific",
    encode: encoders.encodeNeurotransmitter,
    decode: encoders.decodeNeurotransmitter,
    reversible: true,
    tags: ["scientific", "neuroscience", "brain", "chemistry"],
  },
  {
    id: "mantle-convection",
    name: "Mantle Convection",
    description: "Earth mantle flow patterns",
    emoji: "🌋",
    category: "scientific",
    encode: encoders.encodeMantleConvection,
    decode: encoders.decodeMantleConvection,
    reversible: true,
    tags: ["scientific", "geology", "mantle", "geophysics"],
  },
  {
    id: "genetic-algorithm",
    name: "Genetic Algorithm",
    description: "Chromosome/gene representation with fitness scores",
    emoji: "🧬",
    category: "scientific",
    encode: encoders.encodeGeneticAlgorithm,
    decode: encoders.decodeGeneticAlgorithm,
    reversible: true,
    hasSettings: true,
    tags: ["scientific", "genetics", "algorithm", "evolution"],
  },
  {
    id: "cellular-automata",
    name: "Cellular Automata",
    description: "Rule-based binary evolution patterns (Rule 110)",
    emoji: "🦠",
    category: "scientific",
    encode: encoders.encodeCellularAutomata,
    decode: encoders.decodeCellularAutomata,
    reversible: true,
    hasSettings: true,
    tags: ["scientific", "automata", "patterns", "computation"],
  },
  {
    id: "fractal-dimension",
    name: "Fractal Dimension",
    description: "Recursive self-similar nested patterns",
    emoji: "🔄",
    category: "scientific",
    encode: encoders.encodeFractalDimension,
    decode: encoders.decodeFractalDimension,
    reversible: true,
    hasSettings: true,
    tags: ["scientific", "fractal", "recursive", "mathematics"],
  },
  {
    id: "topological",
    name: "Topological (Knot Theory)",
    description: "Knot crossings and twists notation",
    emoji: "🔗",
    category: "scientific",
    encode: encoders.encodeTopological,
    decode: encoders.decodeTopological,
    reversible: true,
    tags: ["scientific", "topology", "knots", "mathematics"],
  },
  {
    id: "synaesthetic",
    name: "Synaesthetic",
    description: "Multi-sensory color/sound/taste mapping",
    emoji: "🎨",
    category: "scientific",
    encode: encoders.encodeSynaesthetic,
    decode: encoders.decodeSynaesthetic,
    reversible: true,
    tags: ["scientific", "synaesthesia", "sensory", "perception"],
  },
  {
    id: "metabolic-pathway",
    name: "Metabolic Pathway",
    description: "Biochemistry enzyme/cofactor notation",
    emoji: "⚗️",
    category: "scientific",
    encode: encoders.encodeMetabolicPathway,
    decode: encoders.decodeMetabolicPathway,
    reversible: true,
    tags: ["scientific", "biochemistry", "metabolism", "enzymes"],
  },
  {
    id: "spike-train",
    name: "Neural Spike Train",
    description: "Neuroscience spike timing patterns",
    emoji: "⚡",
    category: "scientific",
    encode: encoders.encodeSpikeTrain,
    decode: encoders.decodeSpikeTrain,
    reversible: true,
    hasSettings: true,
    tags: ["scientific", "neuroscience", "spikes", "neural"],
  },
];
