import * as encoders from "../encoders/index.js";

export const uniqueEncoders = [
  {
    id: "dna",
    name: "DNA Sequence",
    description: "Encode as genetic base pairs (ATGC)",
    emoji: "🧬",
    category: "unique",
    encode: encoders.encodeDNA,
    decode: encoders.decodeDNA,
    reversible: true,
    tags: ["unique", "biology", "science"],
  },
  {
    id: "playing-cards",
    name: "Playing Cards",
    description: "Express text through card deck",
    emoji: "🃏",
    category: "unique",
    encode: encoders.encodePlayingCards,
    decode: encoders.decodePlayingCards,
    reversible: true,
    tags: ["unique", "cards", "games"],
  },
  {
    id: "chemistry",
    name: "Chemistry Elements",
    description: "Periodic table encoding",
    emoji: "⚗️",
    category: "unique",
    encode: encoders.encodeChemistry,
    reversible: false,
    tags: ["unique", "chemistry", "science"],
  },
  {
    id: "coordinates",
    name: "GPS Coordinates",
    description: "Text as latitude/longitude",
    emoji: "🗺️",
    category: "unique",
    encode: encoders.encodeCoordinates,
    decode: encoders.decodeCoordinates,
    reversible: true,
    tags: ["unique", "geography", "location"],
  },
  {
    id: "zodiac",
    name: "Zodiac Signs",
    description: "Astrological symbol encoding",
    emoji: "♈",
    category: "unique",
    encode: encoders.encodeZodiac,
    decode: encoders.decodeZodiac,
    reversible: true,
    tags: ["unique", "astrology", "mystical"],
  },
  {
    id: "barcode",
    name: "Barcode",
    description: "Visual barcode-style bars",
    emoji: "📊",
    category: "unique",
    encode: encoders.encodeBarcode,
    reversible: false,
    tags: ["unique", "visual", "retail"],
  },
  {
    id: "minecraft",
    name: "Minecraft Blocks",
    description: "Gaming block emojis",
    emoji: "⛏️",
    category: "unique",
    encode: encoders.encodeMinecraft,
    reversible: false,
    tags: ["unique", "gaming", "minecraft"],
  },
  {
    id: "recipe",
    name: "Recipe Cipher",
    description: "Cooking ingredients encoding",
    emoji: "🍳",
    category: "unique",
    encode: encoders.encodeRecipe,
    reversible: false,
    tags: ["unique", "cooking", "food"],
  },
  {
    id: "clock",
    name: "Clock Time",
    description: "Encode as clock times",
    emoji: "🕐",
    category: "unique",
    encode: encoders.encodeClockTime,
    reversible: false,
    tags: ["unique", "time", "clock"],
  },
  {
    id: "weather",
    name: "Weather Symbols",
    description: "Meteorological encoding",
    emoji: "⛅",
    category: "unique",
    encode: encoders.encodeWeather,
    reversible: false,
    tags: ["unique", "weather", "nature"],
  },
  {
    id: "domino",
    name: "Domino Tiles",
    description: "Game piece patterns",
    emoji: "🁣",
    category: "unique",
    encode: encoders.encodeDomino,
    reversible: false,
    tags: ["unique", "games", "tiles"],
  },
  {
    id: "traffic",
    name: "Traffic Signs",
    description: "Road sign symbols",
    emoji: "🛑",
    category: "unique",
    encode: encoders.encodeTrafficSigns,
    reversible: false,
    tags: ["unique", "signs", "roads"],
  },
  {
    id: "tree-pattern",
    name: "Tree Pattern",
    description: "Nature and tree symbols",
    emoji: "🌲",
    category: "unique",
    encode: encoders.encodeTreePattern,
    reversible: false,
    tags: ["unique", "nature", "trees"],
  },
  {
    id: "moon-phase",
    name: "Moon Phases",
    description: "Lunar cycle encoding",
    emoji: "🌙",
    category: "unique",
    encode: encoders.encodeMoonPhase,
    reversible: false,
    tags: ["unique", "moon", "celestial"],
  },
  {
    id: "animal",
    name: "Animal Encoding",
    description: "Cute animal emojis",
    emoji: "🐶",
    category: "unique",
    encode: encoders.encodeAnimal,
    reversible: false,
    tags: ["unique", "animals", "cute"],
  },
  {
    id: "food",
    name: "Food Encoding",
    description: "Delicious food emojis",
    emoji: "🍎",
    category: "unique",
    encode: encoders.encodeFood,
    reversible: false,
    tags: ["unique", "food", "fruit"],
  },
  {
    id: "sports",
    name: "Sports Encoding",
    description: "Athletic sports emojis",
    emoji: "⚽",
    category: "unique",
    encode: encoders.encodeSports,
    reversible: false,
    tags: ["unique", "sports", "games"],
  },
  {
    id: "instruments",
    name: "Musical Instruments",
    description: "Instrument emojis",
    emoji: "🎸",
    category: "unique",
    encode: encoders.encodeInstruments,
    reversible: false,
    tags: ["unique", "music", "instruments"],
  },
  {
    id: "space",
    name: "Space Encoding",
    description: "Cosmic space emojis",
    emoji: "🚀",
    category: "unique",
    encode: encoders.encodeSpace,
    reversible: false,
    tags: ["unique", "space", "cosmic"],
  },
  {
    id: "ocean",
    name: "Ocean Encoding",
    description: "Marine sea life emojis",
    emoji: "🌊",
    category: "unique",
    encode: encoders.encodeOcean,
    reversible: false,
    tags: ["unique", "ocean", "sea"],
  },
  {
    id: "roman",
    name: "Roman Numerals",
    description: "Ancient Roman numbers",
    emoji: "🏛️",
    category: "unique",
    encode: encoders.encodeRomanNumeral,
    reversible: false,
    tags: ["unique", "roman", "numbers", "ancient"],
  },
  {
    id: "number-words",
    name: "Number Words",
    description: "Spelled-out number encoding",
    emoji: "🔢",
    category: "unique",
    encode: encoders.encodeNumberWords,
    reversible: false,
    tags: ["unique", "words", "numbers"],
  },
  {
    id: "hexagram",
    name: "I Ching Hexagrams",
    description: "Ancient Chinese divination",
    emoji: "☯",
    category: "unique",
    encode: encoders.encodeHexagram,
    reversible: false,
    tags: ["unique", "chinese", "mystical"],
  },
  {
    id: "chess",
    name: "Chess Pieces",
    description: "Chess piece encoding",
    emoji: "♔",
    category: "unique",
    encode: encoders.encodeChess,
    reversible: false,
    tags: ["unique", "chess", "games"],
  },
  {
    id: "dice",
    name: "Dice Encoding",
    description: "Roll the dice symbols",
    emoji: "🎲",
    category: "unique",
    encode: encoders.encodeDice,
    reversible: false,
    tags: ["unique", "dice", "games"],
  },
  {
    id: "mahjong",
    name: "Mahjong Tiles",
    description: "Chinese tile game symbols",
    emoji: "🀄",
    category: "unique",
    encode: encoders.encodeMahjong,
    reversible: false,
    tags: ["unique", "mahjong", "chinese", "games"],
  },
  {
    id: "maritime-flags-pro",
    name: "Maritime Flags Pro",
    description: "International maritime flags",
    emoji: "⚓",
    category: "unique",
    encode: encoders.encodeMaritimeFlags,
    reversible: false,
    tags: ["unique", "maritime", "flags"],
  },
  {
    id: "call-sign",
    name: "Ship Call Sign",
    description: "Maritime call sign format",
    emoji: "🚢",
    category: "unique",
    encode: encoders.encodeCallSign,
    reversible: false,
    tags: ["unique", "maritime", "callsign"],
  },
  {
    id: "postal-barcode",
    name: "Postal Barcode",
    description: "Postal barcode pattern",
    emoji: "📮",
    category: "unique",
    encode: encoders.encodePostalBarcode,
    reversible: false,
    tags: ["unique", "postal", "barcode"],
  },
  {
    id: "tracking-number",
    name: "Tracking Number",
    description: "Package tracking format",
    emoji: "📦",
    category: "unique",
    encode: encoders.encodeTrackingNumber,
    reversible: false,
    tags: ["unique", "shipping", "tracking"],
  },
  {
    id: "hospital-code",
    name: "Hospital Code",
    description: "Hospital emergency codes",
    emoji: "🏥",
    category: "unique",
    encode: encoders.encodeHospitalCode,
    reversible: false,
    tags: ["unique", "hospital", "emergency"],
  },
  {
    id: "ems-dispatch",
    name: "EMS Dispatch",
    description: "Emergency dispatch format",
    emoji: "🚑",
    category: "unique",
    encode: encoders.encodeEMS,
    reversible: false,
    tags: ["unique", "ems", "dispatch"],
  },
  {
    id: "isbn-style",
    name: "ISBN Style",
    description: "Book ISBN format",
    emoji: "📚",
    category: "unique",
    encode: encoders.encodeISBN,
    reversible: false,
    tags: ["unique", "isbn", "book"],
  },
  {
    id: "doi-style",
    name: "DOI Style",
    description: "Digital Object Identifier",
    emoji: "🔗",
    category: "unique",
    encode: encoders.encodeDOI,
    reversible: false,
    tags: ["unique", "doi", "academic"],
  },
  {
    id: "call-number",
    name: "Library Call Number",
    description: "Library classification",
    emoji: "📖",
    category: "unique",
    encode: encoders.encodeCallNumber,
    reversible: false,
    tags: ["unique", "library", "dewey"],
  },
  {
    id: "box-drawing-lines",
    name: "Box Drawing Lines",
    description: "┌├┼ box drawing chars",
    emoji: "📊",
    category: "unique",
    encode: encoders.encodeBoxDrawingLines,
    reversible: false,
    tags: ["unique", "box", "drawing"],
  },
  {
    id: "currency-symbols",
    name: "Currency Symbols",
    description: "$€£¥ currency symbols",
    emoji: "💰",
    category: "unique",
    encode: encoders.encodeCurrencySymbols,
    reversible: false,
    tags: ["unique", "currency", "money"],
  },
  {
    id: "card-suits",
    name: "Card Suits",
    description: "♠♣♥♦ card suits",
    emoji: "🃏",
    category: "unique",
    encode: encoders.encodeCardSuits,
    reversible: false,
    tags: ["unique", "cards", "suits"],
  },
  {
    id: "planet-symbols",
    name: "Planet Symbols",
    description: "☿♀♁♂ planetary symbols",
    emoji: "🪐",
    category: "unique",
    encode: encoders.encodePlanetSymbols,
    reversible: false,
    tags: ["unique", "planets", "astronomy"],
  },
  {
    id: "arrow-symbols",
    name: "Arrow Symbols",
    description: "←↑→↓ arrow encoding",
    emoji: "➡️",
    category: "unique",
    encode: encoders.encodeArrowSymbols,
    reversible: false,
    tags: ["unique", "arrows", "direction"],
  },
  {
    id: "geometric-shapes",
    name: "Geometric Shapes",
    description: "●○◐◑ geometric encoding",
    emoji: "⬡",
    category: "unique",
    encode: encoders.encodeGeometricShapes,
    reversible: false,
    tags: ["unique", "geometric", "shapes"],
  },
  {
    id: "dingbats",
    name: "Dingbats",
    description: "✁✂✃✄ dingbat symbols",
    emoji: "✂️",
    category: "unique",
    encode: encoders.encodeDingbats,
    reversible: false,
    tags: ["unique", "dingbats", "symbols"],
  },
];
