import * as encoders from "../encoders/index.js";

export const visualEncoders = [
  {
    id: "sign-language",
    name: "ASL Fingerspelling",
    description: "American Sign Language hand signs",
    emoji: "🤟",
    category: "visual",
    encode: encoders.encodeASL,
    reversible: false,
    tags: ["visual", "asl", "accessibility"],
  },
  {
    id: "seven-segment",
    name: "7-Segment Display",
    description: "Digital display encoding",
    emoji: "🧮",
    category: "visual",
    encode: encoders.encodeSevenSegment,
    reversible: false,
    tags: ["visual", "digital", "display"],
  },
  {
    id: "dancing-men",
    name: "Dancing Men Cipher",
    description: "Sherlock Holmes' Dancing Men",
    emoji: "🕺",
    category: "visual",
    encode: encoders.encodeDancingMen,
    decode: encoders.decodeDancingMen,
    reversible: true,
    tags: ["visual", "cipher", "sherlock"],
  },
  {
    id: "pigpen",
    name: "Pigpen Cipher",
    description: "Geometric substitution cipher",
    emoji: "🔳",
    category: "visual",
    encode: encoders.encodePigpen,
    decode: encoders.decodePigpen,
    reversible: true,
    tags: ["visual", "cipher", "geometric"],
  },
  {
    id: "ascii-box",
    name: "ASCII Box",
    description: "+-----+ style box",
    emoji: "📦",
    category: "visual",
    encode: encoders.encodeASCIIBox,
    reversible: false,
    tags: ["visual", "box", "ascii"],
  },
  {
    id: "fancy-box",
    name: "Fancy Box",
    description: "╔═══╗ style box",
    emoji: "🖼️",
    category: "visual",
    encode: encoders.encodeFancyBox,
    reversible: false,
    tags: ["visual", "box", "fancy"],
  },
  {
    id: "double-box",
    name: "Double Box",
    description: "Double-lined box",
    emoji: "📋",
    category: "visual",
    encode: encoders.encodeDoubleBox,
    reversible: false,
    tags: ["visual", "box", "double"],
  },
  {
    id: "rounded-box",
    name: "Rounded Box",
    description: "╭───╮ rounded corners",
    emoji: "⬜",
    category: "visual",
    encode: encoders.encodeRoundedBox,
    reversible: false,
    tags: ["visual", "box", "rounded"],
  },
  {
    id: "emoji-border",
    name: "Emoji Border",
    description: "🌟 emoji border 🌟",
    emoji: "🌟",
    category: "visual",
    encode: encoders.encodeEmojiBorder,
    reversible: false,
    tags: ["visual", "border", "emoji"],
  },
  {
    id: "star-border",
    name: "Star Border",
    description: "★ star border ★",
    emoji: "★",
    category: "visual",
    encode: encoders.encodeStarBorder,
    reversible: false,
    tags: ["visual", "border", "star"],
  },
  {
    id: "staircase",
    name: "Staircase",
    description: "Diagonal staircase pattern",
    emoji: "📶",
    category: "visual",
    encode: encoders.encodeStaircase,
    reversible: false,
    tags: ["visual", "staircase", "diagonal"],
  },
  {
    id: "reverse-staircase",
    name: "Reverse Staircase",
    description: "Reverse diagonal pattern",
    emoji: "📉",
    category: "visual",
    encode: encoders.encodeReverseStaircase,
    reversible: false,
    tags: ["visual", "staircase", "reverse"],
  },
  {
    id: "pyramid-shape",
    name: "Pyramid Shape",
    description: "Pyramid text pattern",
    emoji: "🔺",
    category: "visual",
    encode: encoders.encodePyramid,
    reversible: false,
    tags: ["visual", "pyramid", "shape"],
  },
  {
    id: "diamond-shape",
    name: "Diamond Shape",
    description: "Diamond text pattern",
    emoji: "💎",
    category: "visual",
    encode: encoders.encodeDiamond,
    reversible: false,
    tags: ["visual", "diamond", "shape"],
  },
  {
    id: "wave-layout",
    name: "Wave Layout",
    description: "Sine wave text layout",
    emoji: "🌊",
    category: "visual",
    encode: encoders.encodeWaveLayout,
    reversible: false,
    tags: ["visual", "wave", "layout"],
  },
  {
    id: "zigzag-pattern",
    name: "Zigzag Pattern",
    description: "Zigzag text layout",
    emoji: "⚡",
    category: "visual",
    encode: encoders.encodeZigzag,
    reversible: false,
    tags: ["visual", "zigzag", "pattern"],
  },
  {
    id: "ascii-banner",
    name: "ASCII Banner",
    description: "Large ASCII art letters",
    emoji: "🎨",
    category: "visual",
    encode: encoders.encodeASCIIBanner,
    reversible: false,
    tags: ["visual", "ascii", "banner"],
  },
  {
    id: "dotted-outline",
    name: "Dotted Outline",
    description: "· dotted outline ·",
    emoji: "⚬",
    category: "visual",
    encode: encoders.encodeDottedOutline,
    reversible: false,
    tags: ["visual", "dotted", "outline"],
  },
];
